Development
eastgenomics/prometheus pull request #1
Opened 2023-08-10 12:16 UTC by PolarisAstrum

2023-08-17 15:17 UTC, chrispyatt requested changes
> Reviewed 7 of 12 files at r1, 4 of 10 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/1)* status: 9 of 18 files reviewed, 35 unresolved discussions (waiting on @PolarisAstrum)

___
*[`bin/compare_annotation.py` line 1 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnH-SQ9miSoIqV3N3i:-NbnH-SQ9miSoIqV3N3j:b8a26gb) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L1)):*
> ```Python
> import re
> ```

documentation - could do with a doc string to explain what the script does
___
*[`bin/compare_annotation.py` line 10 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnH5JyEAaIwT8lOQe2:-NbnH5JyEAaIwT8lOQe3:bteknjt) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L10)):*
> ```Python
> 
> def compare_annotation(diff_twe, diff_tso):
>     # get variant annotation changes for TWE
> ```

documentation - doc string to explain what function does, what the inputs are, what the outputs are
___
*[`bin/compare_annotation.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnM1fS8Eh3tKdqRwkt:-NbnM1fS8Eh3tKdqRwku:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L51)):*
> ```Python
> 
> def parse_diff(diff_filename):
>     # read in file from filename passed in
> ```

docstring
___
*[`bin/compare_annotation.py` line 144 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnOO8p1ztjQSfdsRfR:-NbnOO8p1ztjQSfdsRfS:bprzuhg) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L144)):*
> ```Python
> 
> def parse_line_count(line):
>     # checks if the number of commas is valid when parsing a difference
> ```

can you make the docstring a multi-line comment please, e.g.:



_Code snippet:_
```Python
def my_func:
    """
    Here is my docstring
    """
```
___
*[`bin/compare_annotation.py` line 153 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnOy830CP8Ej9i_Jzb:-NbnOy830CP8Ej9i_Jzc:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L153)):*
> ```Python
>         raise Exception("Invalid (odd) number of commas found when parsing diff file")
> 
> def split_variant_info(raw_list):
> ```

docstring
___
*[`bin/compare_annotation.py` line 163 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnP03d2vxWqVAG9aeR:-NbnP03d2vxWqVAG9aeS:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L163)):*
> ```Python
> 
> def make_tables(added_list, deleted_list, changed_list_from, changed_list_to):
>     # output format: variant category, count TWE, count TSO500
> ```

docstring
___
*[`bin/compare_annotation.py` line 183 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbndBu20zIx398a0B0x:-NbndBu20zIx398a0B0y:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L183)):*
> ```Python
> 
> def get_categories(dataframe_extract):
>     # get full category name from category and info columns for all entries
> ```

docstring
___
*[`bin/compare_annotation.py` line 213 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnkL2DBHkXctb-X2RJ:-NbnkL2DBHkXctb-X2RK:b-btea1u) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L213)):*
> ```Python
>                 if info == ".":
>                     # throw exception, invalid input
>                     print("invalid input")
> ```

should this produce an error here?
___
*[`bin/compare_annotation.py` line 228 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbnkkgd9FPHNPg6YA56:-Nbnkkgd9FPHNPg6YA57:b-r4zhj8) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L228)):*
> ```Python
>                         else:
>                             # throw exception
>                             print("invalid input format in 'info' field")
> ```

error?
___
*[`bin/deployer.py` line 8 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbnlv-T-Q-gzd0DwAze:-Nbnlv-T-Q-gzd0DwAzf:b-5bfsla) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/deployer.py#L8)):*
> ```Python
> 
> def deploy_clinvar_to_production(reference_project_id, dev_project_id, vcf_file_id, tbi_file_id, deploy_folder):
>     # move vcf file and vcf.tbi file to 001 reference project
> ```

docstring - include expected input types
___
*[`bin/deployer.py` line 9 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbu-Phv2pJSSisy-t8l:-Nbu-Phv2pJSSisy-t8m:b-xx9rbf) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/deployer.py#L9)):*
> ```Python
> def deploy_clinvar_to_production(reference_project_id, dev_project_id, vcf_file_id, tbi_file_id, deploy_folder):
>     # move vcf file and vcf.tbi file to 001 reference project
>     vcf_file = dxpy.bindings.dxfile_functions.open_dxfile(dxid=vcf_file_id, project=dev_project_id)
> ```

do you need to close these after cloning or is that done automatically?
___
*[`bin/deployer.py` line 16 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbu-df28ewlGTps-1pJ:-Nbu-df28ewlGTps-1pK:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/deployer.py#L16)):*
> ```Python
> 
> def deploy_testing_to_development(dev_project_id, clinvar_version, added_csv, deleted_csv, changed_csv, job_report):
>     # upload .csv files generated earlier to subfolder of 003 project
> ```

docstring
___
*[`bin/get_clinvar_files.py` line 12 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbobAMTBVXM2xnWzhEh:-NbobAMTBVXM2xnWzhEi:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/get_clinvar_files.py#L12)):*
> ```Python
> 
> def get_ftp_files():
>     clinvar_gz_regex = re.compile("^clinvar_[0-9]+\.vcf\.gz$")
> ```

docstring
___
*[`bin/get_clinvar_files.py` line 36 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nboedau7hEYJ1Cyvlrm:-Nboedau7hEYJ1Cyvlrn:bh4ohk3) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/get_clinvar_files.py#L36)):*
> ```Python
> 
>             if earliest_time < date_object:
>                 print("The date {0} is earlier".format(date_object))
> ```

if you're checking whether date_object is more recent, I think "earlier" is a slightly misleading term
___
*[`bin/get_clinvar_files.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbsI6Qo3sGwxR6qmsUg:-NbsI6Qp0xVzVziwLluK:brolyqr) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/get_clinvar_files.py#L51)):*
> ```Python
> 
> def retrieve_clinvar_files(project_id, download_dir, recent_vcf_file, recent_tbi_file, clinvar_version, genome_build):
>     # validate genome build
> ```

as before - docstring needs explanation of function & also description of inputs and outputs
___
*[`bin/get_clinvar_files.py` line 115 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc2vuNs63umA7VgeBpE:-Nc2vuNs63umA7VgeBpF:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/get_clinvar_files.py#L115)):*
> ```Python
> 
> def run_url_fetcher(project_id, destination_folder,
>                     download_link, new_file_name):
> ```

docstring
___
* [...]

2023-08-18 08:50 UTC, PolarisAstrum reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/1)* status: 8 of 18 files reviewed, 35 unresolved discussions (waiting on @chrispyatt)

___
*[`bin/compare_annotation.py` line 1 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnH-SQ9miSoIqV3N3i:-Nc6jFXqA3NPhr4By4Us:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L1)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

documentation - could do with a doc string to explain what the script does
</blockquote></details>

Done.
___
*[`bin/compare_annotation.py` line 10 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnH5JyEAaIwT8lOQe2:-Nc6jV1mAWXzBEkxHEMo:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L10)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

documentation - doc string to explain what function does, what the inputs are, what the outputs are
</blockquote></details>

Done.
___
*[`bin/compare_annotation.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnM1fS8Eh3tKdqRwkt:-Nc6jZ4f0o70-8UlK5w3:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L51)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/compare_annotation.py` line 144 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnOO8p1ztjQSfdsRfR:-Nc6kn8P6icf_lqX5IIl:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L144)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

can you make the docstring a multi-line comment please, e.g.:
</blockquote></details>

Done.
___
*[`bin/compare_annotation.py` line 153 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnOy830CP8Ej9i_Jzb:-Nc6kp4RAalQxJEpKkpp:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L153)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/compare_annotation.py` line 163 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnP03d2vxWqVAG9aeR:-Nc6kqsIBk41BscksMFd:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L163)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/compare_annotation.py` line 183 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbndBu20zIx398a0B0x:-Nc6krvK3i0xL7HdKqFH:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L183)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/deployer.py` line 8 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbnlv-T-Q-gzd0DwAze:-Nc6kzpe7b9IVpALQgRh:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/deployer.py#L8)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring - include expected input types
</blockquote></details>

Done.
___
*[`bin/deployer.py` line 16 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbu-df28ewlGTps-1pJ:-Nc6l39HC4Q86WCjasgn:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/deployer.py#L16)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/get_clinvar_files.py` line 12 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbobAMTBVXM2xnWzhEh:-Nc6l3wD5sqZNbBJ6dz8:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/get_clinvar_files.py#L12)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/get_clinvar_files.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbsI6Qo3sGwxR6qmsUg:-Nc6l8h2D21PD5pcjfiB:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/get_clinvar_files.py#L51)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

as before - docstring needs explanation of function & also description of inputs and outputs
</blockquote></details>

Done.
___
*[`bin/get_clinvar_files.py` line 115 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc2vuNs63umA7VgeBpE:-Nc6l9a92JUUq9Yrxnfk:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/get_clinvar_files.py#L115)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/get_diff.sh` line 2 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc2wHZWAzoH_WFV-Mwv:-Nc6mRN82IN1lB-gLt-4:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/get_diff.sh#L2)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

some kind of comment to explain the script needed (I know it's obvious), and particularly the arguments passed to the diff command
</blockquote></details>

Done.
___
*[`bin/make_vep_test_configs.py` line 1 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbsg78S9ZIoW80NKdcu:-Nc6n3zdA3u95P8dVdge:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/make_vep_test_configs.py#L1)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/make_vep_test_configs.py` line 52 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc30ISo-Ldldu_942ZX:-Nc6nPPE5aQQMD38FgXC:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/make_vep_test_configs.py#L52)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/make_vep_test_configs.py` line 88 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc30_eo0AvPEWkMF2j6:-Nc6nQ6c4az5r3xT6iRF:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/make_vep_test_configs.py#L88)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/slack_handler.py` line 1 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbsfzbN1SoCIDdt03Lw:-Nc6nY_vChOUBP8eXECI:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/slack_handler.py#L1)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/utils.py` line 1 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbscH-p67THDp_ggIYm:-Nc6ne7GATNnfg6NAVMu:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46 [...]

2023-08-18 15:33 UTC, PolarisAstrum reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/1)* status: 6 of 19 files reviewed, 35 unresolved discussions (waiting on @chrispyatt)

___
*[`bin/compare_annotation.py` line 213 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-NbnkL2DBHkXctb-X2RJ:-Nc7CSvd1VP_4NUF1nTb:b-qukb52) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L213)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

should this produce an error here?
</blockquote></details>

Raising an exception has been added
___
*[`bin/compare_annotation.py` line 228 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbnkkgd9FPHNPg6YA56:-Nc7C_83CD8AZd5TS9wI:b-qukb52) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/compare_annotation.py#L228)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

error?
</blockquote></details>

Raising an exception has been added
___
*[`bin/deployer.py` line 9 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbu-Phv2pJSSisy-t8l:-Nc7EOQd2LC_pw-OUMZ_:b-tzujx4) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/deployer.py#L9)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

do you need to close these after cloning or is that done automatically?
</blockquote></details>

I read through the documentation, and clone does not specify that it closes the file. A close command has been added after opening the DXfile
___
*[`bin/get_clinvar_files.py` line 36 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nboedau7hEYJ1Cyvlrm:-Nc7H0sX3AJVIBKSYYRU:bfvh6ua) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/get_clinvar_files.py#L36)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

if you're checking whether date_object is more recent, I think "earlier" is a slightly misleading term
</blockquote></details>

I renamed all variables from "earliest" to "latest" and "earlier" to "more recent" to avoid ambiguity
___
*[`bin/make_vep_test_configs.py` line 7 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbsg8SmDCGwlxs7-jGb:-Nc8CrrPAs_PvGmMTFwK:b-8syrhj) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/make_vep_test_configs.py#L7)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring - is this checking what the current state in 001 is? What happens if, for some reason, 001 is wiped? (That might be out of scope anyway)
</blockquote></details>

Added check if 001 project exists and if specific folder in 001 exists. raises exception if project or project folder are not found
___
*[`bin/make_vep_test_configs.py` line 34 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc3-WODBU6oJfnxsTvL:-Nc8ErVX5b_DgA5rPllv:b-ljsfhv) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/make_vep_test_configs.py#L34)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

earliest or most recent? (latest?)
</blockquote></details>

Renamed to latest
___
*[`bin/parse.sh` line 2 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc30j8sAwYpWXZx_uyK:-Nc8Gqoj5cG3ntxh7pIR:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/parse.sh#L2)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

same as the other one - quick comment to explain purpose & what bcftools is doing (including any args chosen)
</blockquote></details>

Done.
___
*[`bin/slack_handler.py` line 6 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc318oV8NDgxVlt_bpS:-Nc8FYzY2I0y9YGGsqHF:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/slack_handler.py#L6)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

docstring (for class and methods)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-21 10:53 UTC, chrispyatt requested changes
> Reviewed 2 of 9 files at r5, 1 of 6 files at r6, 2 of 3 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/1)* status: all files reviewed, 3 unresolved discussions (waiting on @PolarisAstrum)

___
*[`bin/deployer.py` line 9 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbu-Phv2pJSSisy-t8l:-NcMVqYzDEvW1bZQ3RP8:b-hi9tc4) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/deployer.py#L9)):*
<details><summary><i>Previously, PolarisAstrum (Polaris Astrum) wrote…</i></summary><blockquote>

I read through the documentation, and clone does not specify that it closes the file. A close command has been added after opening the DXfile
</blockquote></details>

Is it possible to do this as a "with" statement? To prevent the file remaining open if there's an error during the clone process. 



_Code snippet:_
```Python
# normally you do 
with open(file) as f:
    # do stuff
    
    
# I assume this can also be
with open_dxfile(file) as f:
    # do stuff
    
# I could be wrong, but if possible to do then I think that's safer
```


<!-- Sent from Reviewable.io -->

2023-08-21 11:20 UTC, chrispyatt requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/1)* status: all files reviewed, 2 unresolved discussions (waiting on @PolarisAstrum)

___
*[`bin/vep_testing.py` line 92 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc31zuoEI1I8QbUd7aF:-NcMnNGV8gf_KAuzZ5ca:b76opqq) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/vep_testing.py#L92)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

was there no way to do this with e.g. pyvcf? - just wondering as calling external tools is (I think) meant to be slower
</blockquote></details>

something like:



_Code snippet:_
```Python
import vcf

vcf_reader = vcf.Reader(open(r'path\to\vcf', 'rb'))
for record in vcf_reader:
    # %CHROM:%POS:%REF:%ALT %ClinVar %ClinVar_CLNSIG %ClinVar_CLNSIGCONF\n
    # i can't remember how to format strings with loads of inputs
    new_record = "{}\t{}\t{}".format(record.CHROM, record.POS, record.REF, record.ALT, record.INFO["Clinvar"], etc, etc)
    # write to file
```


<!-- Sent from Reviewable.io -->

2023-08-22 10:32 UTC, PolarisAstrum reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/1)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @chrispyatt)

___
*[`bin/deployer.py` line 9 at r3](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nbu-Phv2pJSSisy-t8l:-NcRPOwv0rphiv4MnItm:bsly7bp) ([raw file](https://github.com/eastgenomics/prometheus/blob/e6d0d84831c51c973ae9cdd8c27d46c564b5835c/bin/deployer.py#L9)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

Is it possible to do this as a "with" statement? To prevent the file remaining open if there's an error during the clone process.
</blockquote></details>

That seems to be a good idea in terms of code safety. I Added a with statement
___
*[`bin/get_diff.sh` line 6 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc32cklAn7LK8F0G54w:-NcRQLD5D4HA-anOFDyI:b-4srucw) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/get_diff.sh#L6)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

I've made very little attempt to look up what this actually does so disregard if not relevant but there is a numpy function called numpy.diff - would this be a more pythony way to achieve the same thing? (would require some changes to parse the output I assume but would keep everything in python)
</blockquote></details>

It looks like numpy.diff find the numerical difference between 2 values (e.g., 2 ints, 2 floats), as opposed to the bash diff results for 2 files. So it's not relevant. However, I'll keep it in mind that I should make/remake any bash scripts in Python when possible
___
*[`bin/vep_testing.py` line 92 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/1#-Nc31zuoEI1I8QbUd7aF:-NcRnAtMCr8Ix7xOndBX:bm2163u) ([raw file](https://github.com/eastgenomics/prometheus/blob/0d55c37667741eff81ff3d14865bec2053f912f2/bin/vep_testing.py#L92)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

something like:
</blockquote></details>

The bash script has been replaced with python code using pyvcf


<!-- Sent from Reviewable.io -->

2023-08-29 14:28 UTC, chrispyatt approved these changes
> Reviewed 17 of 17 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PolarisAstrum)



<!-- Sent from Reviewable.io -->

2023-08-29 14:28 UTC, merged