Development 230102
eastgenomics/prometheus pull request #3
Opened 2024-01-02 11:27 UTC by PolarisAstrum-NHS

First working version of Prometheus

2024-01-02 11:28 UTC, pep8speaks commented
Hello @PolarisAstrum-NHS! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

























* In the file [`bin/tests/context.py`](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/context.py):

> [Line 5:1](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/context.py#L5): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 9:1](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/context.py#L9): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 10:1](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/context.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:1](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/context.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 14:1](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/context.py#L14): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 17:1](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/context.py#L17): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 19:1](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/context.py#L19): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

* In the file [`bin/tests/test_annotation_update.py`](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_annotation_update.py):

> [Line 13:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_annotation_update.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 14:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_annotation_update.py#L14): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)

* In the file [`bin/tests/test_compare_annotation.py`](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_compare_annotation.py):

> [Line 79:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_compare_annotation.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 81:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_compare_annotation.py#L81): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 79 characters)



* In the file [`bin/tests/test_inspect_vep_logs.py`](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_inspect_vep_logs.py):

> [Line 12:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_inspect_vep_logs.py#L12): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 13:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_inspect_vep_logs.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 79 characters)

* In the file [`bin/tests/test_inspect_workflow_logs.py`](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_inspect_workflow_logs.py):

> [Line 44:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_inspect_workflow_logs.py#L44): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 45:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_inspect_workflow_logs.py#L45): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 79 characters)
> [Line 46:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_inspect_workflow_logs.py#L46): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)





* In the file [`bin/tests/test_progress_tracker.py`](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_progress_tracker.py):

> [Line 16:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_progress_tracker.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)







* In the file [`bin/tests/test_workflow_handler.py`](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_workflow_handler.py):

> [Line 16:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_workflow_handler.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)
> [Line 17:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_workflow_handler.py#L17): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (177 > 79 characters)
> [Line 18:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_workflow_handler.py#L18): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (177 > 79 characters)
> [Line 19:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_workflow_handler.py#L19): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (177 > 79 characters)
> [Line 20:80](https://github.com/eastgenomics/prometheus/blob/9382b52e17aae1f9fa4c1cc02e8a564c09ec214e/bin/tests/test_workflow_handler.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (177 > 79 characters)

2024-01-15 13:49 UTC, jethror1 requested changes
> Reviewed 2 of 35 files at r2, 3 of 16 files at r3, 1 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 6 of 38 files reviewed, 34 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @PolarisAstrum-NHS)

___
*[`bin/annotation/annotation_update.py` line 34 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC-9631VD1wvnbZFbI:-NoC-9631VD1wvnbZFbJ:bqwsksa) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L34)):*
> ```Python
>         os.mkdir("temp")
>     except FileExistsError:
>         pass
> ```

alternative to this is `os.makedirs()` which accepts `exist_ok=True` to handle existing directories like `mkdir -p` in bash does

https://docs.python.org/3/library/os.html#os.makedirs



_Code quote:_
```Python
    try:
        os.mkdir("temp")
    except FileExistsError:
        pass
```
___
*[`bin/annotation/annotation_update.py` line 49 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC0iMFCivginJwF-pB:-NoC0iMGD1y1JIaYCyKD:b-gt2607) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L49)):*
> ```Python
>      clinvar_version) = get_ftp_files()
>     update_folder = ("/ClinVar_version_{}_annotation_resource_update"
>                      .format(clinvar_version))
> ```

I'd consider using f strings over `.format` as I find them much more readable (especially when you get more complex strings):

```
update_folder = (
    f"ClinVar_version_{clinvar_version}_annotation_resource_update"
)
```



_Code quote:_
```Python
    update_folder = ("/ClinVar_version_{}_annotation_resource_update"
                     .format(clinvar_version))
```
___
*[`bin/annotation/annotation_update.py` line 76 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC-yu80onhZUa7q-DQ:-NoC-yu80onhZUa7q-DR:b-kwzyfw) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L76)):*
> ```Python
>                                                  recent_tbi_file,
>                                                  earliest_time)
>                     + " have already been downloaded")
> ```

f string here I think would be good, this could be rewritten something like:

```
logger.info(
    f"The clinvar annotation resource files {recent_vcf_file} and "
    f"{recent_tbi_file} from {earliest_time} have already been downloaded"
)
```

also multi line strings inside parentheses don't need `+` as they automatically get joined



_Code quote:_
```Python
        logger.info("The clinvar annotation resource files "
                    + "{} and {} from {}".format(recent_vcf_file,
                                                 recent_tbi_file,
                                                 earliest_time)
                    + " have already been downloaded")
```
___
*[`bin/annotation/annotation_update.py` line 87 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC1INu0ZvfvjGzn307:-NoC1INu0ZvfvjGzn308:b-vc36w9) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L87)):*
> ```Python
>     if not tracker.configs_made:
>         logger.info("Creating development and production "
>                     + "config files from template")
> ```

no need for the `+`

```
logger.info(
    "Creating development and production config files from template"
)

```



_Code quote:_
```Python
        logger.info("Creating development and production "
                    + "config files from template")
```
___
*[`bin/annotation/annotation_update.py` line 104 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC1_Yf465JqALRWctD:-NoC1_Yf465JqALRWctE:b-ih85tn) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L104)):*
> ```Python
>     tracker.check_configs_made()
>     if not tracker.configs_made:
>         raise Exception("Config files were not uploaded to DNAnexus")
> ```

generally best to avoid raising a bare Exception as it can hide other bugs and make it hard to catch, a more appropriate generic error type in python to raise is a `RuntimeError` 



_Code quote:_
```Python
Exception
```
___
*[`bin/annotation/compare_annotation.py` line 30 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCKsiF45j5InrkrNPA:-NoCKsiGAnpNb4F_C-bI:b-rzq3yd) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L30)):*
> ```Python
>     # get variant annotation changes for TWE
>     added_twe, deleted_twe, changed_twe, detailed_twe = parse_diff(diff_twe,
>                                                                    bin_folder)
> ```

I think this indentation is against pep8 and seems to show up red in linting, consider dropping to new lines after parentheses (this really helps where you have nested indentation to prevent it getting really long:
```
added_twe, deleted_twe, changed_twe, detailed_twe = parse_diff(
    diff_twe, bin_folder
)
```



_Code quote:_
```Python
    added_twe, deleted_twe, changed_twe, detailed_twe = parse_diff(diff_twe,
                                                                   bin_folder)
```
___
*[`bin/annotation/compare_annotation.py` line 190 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCLPvc8XAzoCe3aveW:-NoCLPvdAnuygPylle_F:b43at1q) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L190)):*
if you need to access the index of an iterable, `enumerate()` is nicer:
```
>>> l = ['a', 'b', 'c']
>>> for idx, val in enumerate(l):
...     print(f"{idx}: {val}")
... 
0: a
1: b
2: c
```



_Code quote:_
```Python
for i in range(0, len(changed_from_split)):
```
___
*[`bin/annotation/compare_annotation.py` line 192 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCLpJ19dVxsbiov2rG:-NoCLpJ19dVxsbiov2rH:b-8l9esp) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L192)):*
> ```Python
>     for i in range(0, len(changed_from_split)):
>         from_name = changed_from_split[i][2]
>         to_name = changed_to_split[i][2]
> ```

calling `.strip()` on these would save the double checking of empty string or space below



_Code quote:_
```Python
        from_name = changed_from_split[i][2]
        to_name = changed_to_split[i][2]
```
___
*[`bin/annotation/get_clinvar_files.py` line 94 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCN5EnCqO_21sah428:-NoCN5EnCqO_21sah429:b-f3j7is) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/get_clinvar_files.py#L94)):*
> ```Python
>     build_number = genome_build[1:]
>     vcf_link = ("https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh"
>                 + "{}/weekly/{}".format(build_number, recent_vcf_file))
> ```

I think these base URLs would be better in the config to make it easier to fix if they change the hosting end point



_Code quote:_
```Python
    vcf_link = ("https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh"
                + "{}/weekly/{}".format(build_number, recent_vcf_file))
```
___
*[`bin/annotation/get_clinvar_files.py` line 173 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCMlEn-rsVz1JwoEMH:-NoCMlEn-rsVz1JwoEMI:b2vm2xi) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/get_clinvar_files.py#L173)):*
> ```Python
>                 priority='high'
>             )
>     job_id = job.describe().get('id') [...]

2024-01-16 09:27 UTC, JasonLing95 requested changes
> Reviewed 14 of 35 files at r2, 4 of 16 files at r3, 9 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 27 of 38 files reviewed, 55 unresolved discussions (waiting on @corbin-chris and @PolarisAstrum-NHS)

___
*[`bin/tests/context.py` line 5 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCZH_ABNhRFJYNIoNz:-NoCZH_ABNhRFJYNIoO-:bhk1m0p) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/context.py#L5)):*
> ```Python
> sys.path.insert(0, os.path.abspath('..'))
> 
> import annotation.annotation_update as annotation_update
> ```

```
import annotation.annotation_update
```
should be sufficient to call annotation_update()
___
*[`bin/tests/test_compare_annotation.py` line 13 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCZYu0DMc_r5bBlCmf:-NoCZYu0DMc_r5bBlCmg:b-fg5w3y) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L13)):*
> ```Python
> class testCase(unittest.TestCase):
> 
>     def test_regex(self):
> ```

docstring on what this is testing and expectation. same for other unit test functions
___
*[`bin/tests/test_compare_annotation.py` line 95 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCZsCr7aKjPCpK0qF2:-NoCZsCr7aKjPCpK0qF3:b-by50ev) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L95)):*
> ```Python
>         # check output type is correct
>         assert ((type(added_df) is pandas.DataFrame)
>                 and (type(deleted_df) is pandas.DataFrame)
> ```

is compare object identity rather than value equality. I assume you want to compare both their value so "==" should be the correct operator in this case.
___
*[`bin/tests/test_compare_annotation.py` line 130 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_F-h1TNeRT3McTnF:-NoC_F-h1TNeRT3McTnG:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L130)):*
> ```Python
>         assert output[0][3] == "."
> 
>     def test_get_evidence_counts(self):
> ```

docstring
___
*[`bin/tests/test_compare_annotation.py` line 138 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_Hf5CPmM3tx7y1lb:-NoC_Hf5CPmM3tx7y1lc:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L138)):*
> ```Python
>         assert ca.get_evidence_counts(input) == [1, 0, 0, 31, 46, 0, 0]
> 
>     def test_make_dataframes(self):
> ```

docstring
___
*[`bin/tests/test_inspect_vep_logs.py` line 9 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_NMk9mCVxw3fhjHe:-NoC_NMk9mCVxw3fhjHf:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_inspect_vep_logs.py#L9)):*
> ```Python
> 
> 
> class testCase(unittest.TestCase):
> ```

docstring
___
*[`bin/tests/test_login_handler.py` line 20 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_yNNBtMvBXDac09x:-NoC_yNNBtMvBXDac09y:b5w8i1z) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_login_handler.py#L20)):*
> ```Python
>         login = lh.LoginHandler()
>         dx_token, slack_token = login.load_credentials()
>         assert re.match(r".{32}", dx_token)
> ```

i see that login_handler raise exception if dnanexus login with token failed. the unit test should test for exception raised instead
___
*[`bin/tests/test_progress_tracker.py` line 28 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCaHw8ARNC7J8_CX6i:-NoCaHw8ARNC7J8_CX6j:b1kfpum) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_progress_tracker.py#L28)):*
> ```Python
>         tracker_b37 = Tracker(dev_proj_id, ref_proj_id, update_folder,
>                               b37_folder, genome_build, clinvar_version)
>         assert type(tracker_b37) is Tracker
> ```

this assertion is not useful
___
*[`bin/tests/test_progress_tracker.py` line 30 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCaFxC3K5pZWLdhK1l:-NoCaFxDDaOG_2ZgKQPB:b4fa8k6) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_progress_tracker.py#L30)):*
> ```Python
>         assert type(tracker_b37) is Tracker
> 
>         assert tracker_b37.perform_checks() is None
> ```

could you explain why it will be None
___
*[`bin/tests/test_slack_handler.py` line 19 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCabAaDkvPjiSSm8FV:-NoCabAaDkvPjiSSm8FW:b-ltmy0b) ([raw file](https://github.com/eastgenomics/prometheus/blob/ac1762166e470b6237b5ace4f73c98b26d37bb82/bin/tests/test_slack_handler.py#L19)):*
> ```Python
>             handler.send_message("egg-test", test_message)
> 
>     def test_login_invalid_channel(self):
> ```

it might be better to have one unit test function - testing one single output rather than one big function having multiple assertions

makes it easier to keep track if there's unit test failing
___
*[`bin/tests/test_utils.py` line 17 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCaljx2E8GoOoAxf_K:-NoCaljx2E8GoOoAxf_L:b-5h08c7) ([raw file](https://github.com/eastgenomics/prometheus/blob/ac1762166e470b6237b5ace4f73c98b26d37bb82/bin/tests/test_utils.py#L17)):*
> ```Python
>         assert not check_project_exists(test_proj_id)
> 
>     def test_valid_proj_id(self):
> ```

same here.
___
*[`bin/tests/test_vep_testing.py` line 39 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCauKe8vnYMrsOfZhv:-NoCauKe8vnYMrsOfZhw:b9h4v8) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_vep_testing.py#L39)):*
> ```Python
>         os.remove("test_prod.txt")
> 
>     def test_make_job_report(self):
> ```

docstring
___
*[`bin/annotation/annotation_update.py` line 145 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCOzOzCUuCcU5CoUWE:-NoCOzP--WSNdfz3LsUS:boa1qae) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L145)):*
> ```Python
>                                   dev_proj_id, update_folder)
>         else:
>             Exception("Clinvar changes status could not be checked")
> ```

raise Exception
___
*[`bin/annotation/compare_annotation.py` line 279 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCRZlbB7eY1JnqYR37:-NoCRZlbB7eY1JnqYR38:b-z4l7di) ([raw file](https://github.com/eastgenomics/prometheus/blob/ac1762166e470b6237b5ace4f73c98b26d37bb82/bin/annotation/compare_annotation.py#L279)):*
> ```Python
>     # generate variant evidence report
>     # get all changed variants
>     detailed_df = changed_from_df[["changed from",
> ```

why make the description of the var more ambiguous
___
*[`bin/annotation/compare_annotation.py` line 328 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCRegX-3xj8xW3ubns:-NoCRegY35W_TiieGp7M:b-idozxw) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L328)):*
> ```Python
> 
>     # TODO: handle case for only evidence count changing (e.g., (1) to (2))
>     ev_df = pandas.DataFrame(data=evidence_list,
> ```

more descriptive var name please
___
*[`bin/annotation/compare_annotation.py` line 371 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCS_8K1BoKnQE0DqNQ:-NoCS_8L4UZbKPg-92K-:bmyz5bf) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f8 [...]

2024-01-16 11:09 UTC, corbin-chris requested changes
> Reviewed 2 of 19 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 29 of 38 files reviewed, 65 unresolved discussions (waiting on @PolarisAstrum-NHS)

___
*[`bin/tests/test_compare_annotation.py` line 11 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGlln33Kh9ewDdGX_C:-NoGlln33Kh9ewDdGX_D:b-78g4gh) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L11)):*
> ```Python
> 
> 
> class testCase(unittest.TestCase):
> ```

Give this a more informative name than testCase. TestCompareAnnotations maybe
___
*[`bin/tests/test_compare_annotation.py` line 86 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGlyDjEOkQXDo_IZUt:-NoGlyDjEOkQXDo_IZUu:b-2j9jt6) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L86)):*
> ```Python
>         with open("test_diff.txt", "w") as f:
>             f.write(parse_text)
>             f.write("\n")
> ```

You can save a lot of creating new files and then deleting them by using Python mocks instead. This means your test is no longer dependent on the file system.
Examples of mock_open are here: https://github.com/eastgenomics/hgnc_check_fusions/blob/main/tests/test_hgnc_check_fusions.py. Instead of there being a real test file that is opened, the function test_open_fusion_list_correct_input() creates a mock file instead, with the specified contents.
This isn't essential to continue but is a very useful skill to start building now, especially if you ever have to test databases.
___
*[`bin/tests/test_progress_tracker.py` line 13 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGuZwABlcf81i2H9xx:-NoGuZwBEFymGKrLi-uz:bnn5qhk) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_progress_tracker.py#L13)):*
> ```Python
> 
> 
> class testCase(unittest.TestCase):
> ```

Please use a more informative name for your testCase!
___
*[`bin/tests/test_vep_testing.py` line 55 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGfpSiBMqY9AJT6-fj:-NoGfpSiBMqY9AJT6-fk:b-a0t5lb) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_vep_testing.py#L55)):*
> ```Python
>             os.remove(output)
> 
>     def test_get_recent_vep_vcf_bed(self):
> ```

Docstring here too (and anywhere else in the tests that's missing one). Please always explain what you're trying to test
___
*[`bin/annotation/compare_annotation.py` line 247 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGwOX96wiywQcbgqK2:-NoGwOX96wiywQcbgqK3:bgswlp7) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L247)):*
> ```Python
>     for item in raw_list:
>         # format: mutation, clinvar ID, category, info
>         # ignore first element as this is ">" or "<"
> ```

I'd add a check for the first element being '>' - if it isn't you know something has gone really wrong and can throw an error
___
*[`bin/annotation/compare_annotation.py` line 277 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGvEBj3Z_mZ1fyMH8m:-NoGvEBj3Z_mZ1fyMH8n:b-x83k4y) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L277)):*
> ```Python
>     """
>     added_df = pandas.DataFrame(data=added_list,
>                                 columns=["mutation", "clinvar ID",
> ```

I'd put the columns you use over and over again in a list at the top of make_dataframes. Then you can pass the list to 'columns' when you make DataFrames.
It's generally safer to do this for variables you're reusing a lot. Less risk of a copy-paste mistake causing weird problems later.



_Code snippet:_
```Python
standard_cols = ["mutation", "clinvar ID", "category", "info"]

added_df = pandas.DataFrame(data=added_list, columns=standard_cols)
```
___
*[`bin/annotation/compare_annotation.py` line 464 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGs0MQDR29ezxAKbYv:-NoGs0MQDR29ezxAKbYw:bpmscve) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L464)):*
> ```Python
>     Args:
>         base_name (str): from category column
>         info (str): from info column
> ```

add regex_dict to args list
___
*[`bin/annotation/compare_annotation.py` line 499 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGsCiu5EfnaexuUUvl:-NoGsCiu5EfnaexuUUvm:buy1pin) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L499)):*
> ```Python
>                         and key != conflict_other
>                         and key != conflict_risk
>                         and key != conflict_other_risk):
> ```

I think this would work just as well and save some words:



_Code snippet:_
```Python
if key not in [conflict, conflict_other, conflict_other, conflict_other_risk]

# Or even just this, and get rid of the 'conflict', 'conflict_other', 'conflict_other_risk' variables, as you never use them again
conflict_labels = ["conflicting interpretations of pathogenicity and other", "conflicting interpretations of pathogenicity and risk factor", "conflicting interpretations of pathogenicity and other and risk factor"]
if key not in conflict_labels:
    full_names.append(key)    
```
___
*[`bin/util/vep_testing.py` line 33 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGjUimDyUlpRlUEgDe:-NoGjUimDyUlpRlUEgDf:b-ueec1t) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L33)):*
> ```Python
>         dx_update_folder (str): dev folder for current vep update
>         ref_proj_id (str): DNAnexus project ID for 001 reference
>         assay (str): vep assay name
> ```

Please check every one of your docstrings before the next review round. You seem to be missing args from many of them.
___
*[`bin/util/vep_testing.py` line 308 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGg9ob3vvOBA5nm7Fj:-NoGg9ob3vvOBA5nm7Fk:b-e1gjrs) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L308)):*
> ```Python
> 
>     Args:
>         assay (str): name of assay
> ```

Explain the args 'ref_proj_id' and 'genome_build' too please.
Ideally also specify the argument and return types, if it's a newish version of Python. 
That would look like this:



_Code snippet:_
```Python
def get_recent_vep_vcf_bed(assay: str, ref_proj_id: str, genome_build: str) -> tuple[str, str]
```


<!-- Sent from Reviewable.io -->

2024-01-16 11:09 UTC, JasonLing95 requested changes
> Reviewed 5 of 19 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 32 of 38 files reviewed, 78 unresolved discussions (waiting on @PolarisAstrum-NHS)

___
*[`bin/util/progress_tracker.py` line 19 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGe-m99DqGns80riYf:-NoGe-m99DqGns80riYg:b-kq86ah) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L19)):*
> ```Python
>     """Checks and records update steps already performed
>     """
>     STATUS_UNCHECKED = "unchecked"
> ```

is this defined as a class variable so that it can be changed outside of the class later on or it's more of an instance variable when the class is defined? If the latter, then just define it in the __init__ else ignore me
___
*[`bin/util/progress_tracker.py` line 174 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGcwnt2JKDz6yNsAyh:-NoGcwnt2JKDz6yNsAyi:b-vowep2) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L174)):*
> ```Python
> 
>         # perform review to check if changes can be passed automatically
>         changed = pd.read_csv(download_dest)
> ```

can this var name be changed to "changed_df" rather than having the same var name as the var above which define the filename
___
*[`bin/util/progress_tracker.py` line 179 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGdLL--U0GPFYhv7xg:-NoGdLL--U0GPFYhv7xh:bosz902) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L179)):*
> ```Python
>         patho_1 = "pathogenic"
>         patho_2 = "pathogenic/likely pathogenic"
>         for index, row in changed.iterrows():
> ```

could add a comment on why this logic
___
*[`bin/util/progress_tracker.py` line 186 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGdHoo4oOdh_JvBQrm:-NoGdHoo4oOdh_JvBQrn:b-wbv90x) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L186)):*
> ```Python
>                 self.changes_status == self.STATUS_REVIEW
>                 return
>             if ((row["changed to"] == benign_1
> ```

combine with above into one if statement
___
*[`bin/util/progress_tracker.py` line 229 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGeAVOEvH8c2i0ZTxr:-NoGeAVP8aux-fwvd7t3:b-8euyd0) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L229)):*
> ```Python
>     """Checks and records update steps already performed
>     """
>     STATUS_UNCHECKED = "unchecked"
> ```

same for this one - is this necessary or do you just want an instance variable within the class itself
___
*[`bin/util/slack_handler.py` line 80 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGqPu20g6brGXtLxG3:-NoGqPu20g6brGXtLxG4:b-uo0ab9) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/slack_handler.py#L80)):*
> ```Python
>             Exception: Error sending slack notification
>         """
>         full_message = "🔥 Prometheus: " + message
> ```

will the fire emoji translate in Slack msg?
___
*[`bin/util/utils.py` line 474 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGtcKE64xSpcFAwb-g:-NoGtcKE64xSpcFAwb-h:b-77zt52) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L474)):*
> ```Python
>         raise Exception("Regex {} had no match in file {}"
>                         .format(replace_regex, old_config_filename))
>     os.remove(old_config_filename)
> ```

is there a possibility of os.remove to raise exception if old_config_filename is not there. better to wrap in try except
___
*[`bin/util/utils.py` line 618 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGucGVBAcBC56g4WMk:-NoGucGVBAcBC56g4WMl:b-c3shu5) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L618)):*
> ```Python
>                         + " in past {} months".format(months))
> 
>     assay_info = [[]]
> ```

i think a list here is enough to make df later on
___
*[`bin/util/utils.py` line 631 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGuwmGEguUJa4kR3Ih:-NoGuwmGEguUJa4kR3Ii:bldh6uj) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L631)):*
> ```Python
>                                             "created"])
>     # sort by date
>     df = df.sort_values(["created"], ascending=[False])
> ```

could do with just bool rather than list of bool
___
*[`bin/util/utils.py` line 645 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGv2HS0zYKxZBlGlDd:-NoGv2HS0zYKxZBlGlDe:b-sbrdjr) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L645)):*
> ```Python
>         name (str): name of DNAnexus file
>     """
>     file = dxpy.bindings.dxfile.DXFile(file_id)
> ```

might want to try clause DXFile if file-id doesn't exist
___
*[`bin/util/vep_testing.py` line 14 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGvrqDA7npE4oaGm8Z:-NoGvrqDA7npE4oaGm8_:bberyzr) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L14)):*
> ```Python
> 
> # local modules
> import annotation.compare_annotation as compare_annotation
> ```

"as compare_annotation"w is not needed
___
*[`bin/util/vep_testing.py` line 53 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGwJKi4znya6IMqc2P:-NoGwJKi4znya6IMqc2Q:b-lcb3cg) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L53)):*
> ```Python
>     os.system("dx watch {} > {}".format(vep_job, log))
> 
>     config_name = DXFile(dxid=dev_config_id,
> ```

try clause if dxid or project is invalid
___
*[`bin/util/vep_testing.py` line 202 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGxWFq8wPNb_WaXo7_:-NoGxWFr8cduZk80xhZL:buff18v) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L202)):*
> ```Python
>     with open(vcf_output_path, "w") as file:
>         for record in vcf_reader:
>             csq_fields = (record.INFO["CSQ"][0]).split("|")
> ```

is there a chance this won't split() into list of 5 values?


<!-- Sent from Reviewable.io -->

2024-01-16 11:27 UTC, JasonLing95 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 32 of 38 files reviewed, 78 unresolved discussions (waiting on @PolarisAstrum-NHS)

___
*[`bin/vep_config/vep_config_update.py` line 13 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGy0yU3x4BaQw3SGeM:-NoGy0yU3x4BaQw3SGeN:bavn6tn) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/vep_config/vep_config_update.py#L13)):*
> ```Python
> import sys
> 
> import util.vep_testing as vep_testing
> ```

"as vep_testing" not required
___
*[`bin/vep_config/vep_config_update.py` line 41 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGyWHrERGi8MbjkYbB:-NoGyWHrERGi8MbjkYbC:b-yzbnjc) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/vep_config/vep_config_update.py#L41)):*
> ```Python
>     # make temp dir
>     try:
>         os.mkdir("temp")
> ```

could use mkdir(exist_ok=True)


<!-- Sent from Reviewable.io -->

2024-01-16 11:36 UTC, JasonLing95 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 32 of 38 files reviewed, 80 unresolved discussions (waiting on @PolarisAstrum-NHS)

___
*[`bin/vep_config/vep_config_update.py` line 201 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoH1Jq64ZIWgMWgYubD:-NoH1Jq64ZIWgMWgYubE:b48m8c4) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/vep_config/vep_config_update.py#L201)):*
> ```Python
>     # Verification that step 1 has been completed
>     tracker.check_pr_merged()
>     if not tracker.pr_merged:
> ```

what's the next step if pr is not merged, is it manual intervention?
___
*[`bin/vep_config/vep_config_update.py` line 353 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoH2Y0RC_k821kRHVm6:-NoH2Y0RC_k821kRHVm7:bma8y42) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/vep_config/vep_config_update.py#L353)):*
> ```Python
>     # Followed by the genome build e.g., b38
> 
>     # validate arguments
> ```

docstring on what args are required and example cmd


<!-- Sent from Reviewable.io -->

2024-01-17 09:44 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 13 of 38 files reviewed, 80 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/annotation/annotation_update.py` line 49 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC0iMFCivginJwF-pB:-NoHQZMr6qSBYOQ_vmbP:bvguqcp) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L49)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'd consider using f strings over `.format` as I find them much more readable (especially when you get more complex strings):

```
update_folder = (
    f"ClinVar_version_{clinvar_version}_annotation_resource_update"
)
```
</blockquote></details>

I agree, it definitely makes the code more readable. I've changed the string.format instances to f strings
___
*[`bin/annotation/annotation_update.py` line 76 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC-yu80onhZUa7q-DQ:-NoHRF2c22Sg2Gm5de6S:bb6un1j) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L76)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

f string here I think would be good, this could be rewritten something like:

```
logger.info(
    f"The clinvar annotation resource files {recent_vcf_file} and "
    f"{recent_tbi_file} from {earliest_time} have already been downloaded"
)
```

also multi line strings inside parentheses don't need `+` as they automatically get joined
</blockquote></details>

Done
___
*[`bin/annotation/annotation_update.py` line 87 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC1INu0ZvfvjGzn307:-NoHRMAR1E68YRtOkaz2:bb6un1j) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L87)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

no need for the `+`

```
logger.info(
    "Creating development and production config files from template"
)

```
</blockquote></details>

Done
___
*[`bin/annotation/annotation_update.py` line 104 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC1_Yf465JqALRWctD:-NoLWw-p1av_-AkWtd36:bccb5gu) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L104)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

generally best to avoid raising a bare Exception as it can hide other bugs and make it hard to catch, a more appropriate generic error type in python to raise is a `RuntimeError`
</blockquote></details>

Done. Raising Exception has been replaced with RuntimeError or a slack notification where appropriate
___
*[`bin/annotation/annotation_update.py` line 145 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCOzOzCUuCcU5CoUWE:-NoHb7bP-FKuTPSzBzkx:bzca81l) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L145)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

raise Exception
</blockquote></details>

Replaced exception with slack notification
___
*[`bin/annotation/compare_annotation.py` line 30 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCKsiF45j5InrkrNPA:-NoLXJIB8RPjYMShzc0m:biuf23) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L30)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think this indentation is against pep8 and seems to show up red in linting, consider dropping to new lines after parentheses (this really helps where you have nested indentation to prevent it getting really long:
```
added_twe, deleted_twe, changed_twe, detailed_twe = parse_diff(
    diff_twe, bin_folder
)
```
</blockquote></details>

Done. Code indentation has been reformatted to improve readability
___
*[`bin/util/progress_tracker.py` line 19 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGe-m99DqGns80riYf:-NoLePuIBrV4E_W8c2vt:b-f9deuk) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L19)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

is this defined as a class variable so that it can be changed outside of the class later on or it's more of an instance variable when the class is defined? If the latter, then just define it in the __init__ else ignore me
</blockquote></details>

These are constants and only need to be defined once. Python lacks an explicit constant type so I have to rely on the use of capitals
___
*[`bin/util/progress_tracker.py` line 174 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGcwnt2JKDz6yNsAyh:-NoLfaNFEX2m3Xd7Cqs8:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L174)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

can this var name be changed to "changed_df" rather than having the same var name as the var above which define the filename
</blockquote></details>

Done.
___
*[`bin/util/progress_tracker.py` line 179 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGdLL--U0GPFYhv7xg:-NoLg5ZF7oHt_nZA3I0a:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L179)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could add a comment on why this logic
</blockquote></details>

Done.
___
*[`bin/util/progress_tracker.py` line 186 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGdHoo4oOdh_JvBQrm:-NoLhvVSCzkX6aKVrb2O:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L186)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

combine with above into one if statement
</blockquote></details>

Done.
___
*[`bin/util/progress_tracker.py` line 229 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGeAVOEvH8c2i0ZTxr:-NoLi-810oiWJbmS98L1:b-2ufr8f) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/progress_tracker.py#L229)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same for this one - is this necessary or do you just want an instance variable within the class itself
</blockquote></details>

These are constants
___
*[`bin/util/slack_handler.py` line 80 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGqPu20g6brGXtLxG3:-NoLiD1L0JXkpAk2Of99:b1489cb) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/slack_handler.py#L80)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

will the fire emoji translate in Slack msg?
</blockquote></details>

Yes, and it has been well tested
___
*[`bin/util/utils.py` line 134 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC4nnNBnw2omeRKGoi:-NoLiPnK6D4s7d3TZQ54:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L134)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'd try avoid raising bare exceptions to limit error hiding, `RuntimeError` might be more appropriate, Python  [...]

2024-01-18 15:41 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 12 of 38 files reviewed, 80 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/tests/context.py` line 5 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCZH_ABNhRFJYNIoNz:-NoR5_K87oIX1twKIiEs:b-uq0do1) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/context.py#L5)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

```
import annotation.annotation_update
```
should be sufficient to call annotation_update()
</blockquote></details>

Removing "as annotation_update" breaks the import
___
*[`bin/tests/test_compare_annotation.py` line 86 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGlyDjEOkQXDo_IZUt:-NoR5rZ22pYUpw0AC1lh:b-ae7biq) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L86)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You can save a lot of creating new files and then deleting them by using Python mocks instead. This means your test is no longer dependent on the file system.
Examples of mock_open are here: https://github.com/eastgenomics/hgnc_check_fusions/blob/main/tests/test_hgnc_check_fusions.py. Instead of there being a real test file that is opened, the function test_open_fusion_list_correct_input() creates a mock file instead, with the specified contents.
This isn't essential to continue but is a very useful skill to start building now, especially if you ever have to test databases.
</blockquote></details>

Thanks. I meant to look into this earlier but never got around to it. That seems a lot simpler than relying on the file system
___
*[`bin/tests/test_compare_annotation.py` line 95 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCZsCr7aKjPCpK0qF2:-NoR6qS6BQ2IFqHt9TUx:beqisyx) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L95)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

is compare object identity rather than value equality. I assume you want to compare both their value so "==" should be the correct operator in this case.
</blockquote></details>

My linter complained when I tried that before "do not compare types, for exact checks use \`is\` / \`is not\`, for instance checks use \`isinstance()\`Flake8(E721)". However, I found I can use isinstance instead
___
*[`bin/tests/test_progress_tracker.py` line 28 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCaHw8ARNC7J8_CX6i:-NoS-7_tA8P7TVFswKsX:b-mpr8rw) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_progress_tracker.py#L28)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this assertion is not useful
</blockquote></details>

This was initially added to check if the Tracker was instantiated correctly, but it would fail before reaching the assertion if that were the case anyway. It's removed now
___
*[`bin/tests/test_progress_tracker.py` line 30 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCaFxC3K5pZWLdhK1l:-NoS0KqO1bUe-UCc6OBp:b-p49jnx) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_progress_tracker.py#L30)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could you explain why it will be None
</blockquote></details>

This is just checking that the method perform_checks runs successfully. It has no return type, so it can only return None
___
*[`bin/tests/test_slack_handler.py` line 19 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCabAaDkvPjiSSm8FV:-NoS1mFF7OXQFrkKoIOC:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/ac1762166e470b6237b5ace4f73c98b26d37bb82/bin/tests/test_slack_handler.py#L19)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

it might be better to have one unit test function - testing one single output rather than one big function having multiple assertions

makes it easier to keep track if there's unit test failing
</blockquote></details>

Done.
___
*[`bin/tests/test_utils.py` line 17 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCaljx2E8GoOoAxf_K:-NoS5vfC54pDDR6hsX5Q:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/ac1762166e470b6237b5ace4f73c98b26d37bb82/bin/tests/test_utils.py#L17)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.
___
*[`bin/annotation/annotation_update.py` line 34 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC-9631VD1wvnbZFbI:-NoMtEWd0ghNm3yE7WcD:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/annotation_update.py#L34)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

alternative to this is `os.makedirs()` which accepts `exist_ok=True` to handle existing directories like `mkdir -p` in bash does

https://docs.python.org/3/library/os.html#os.makedirs
</blockquote></details>

Done.
___
*[`bin/annotation/compare_annotation.py` line 190 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCLPvc8XAzoCe3aveW:-NoMuCis2ga-im6Dk2fg:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L190)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you need to access the index of an iterable, `enumerate()` is nicer:
```
>>> l = ['a', 'b', 'c']
>>> for idx, val in enumerate(l):
...     print(f"{idx}: {val}")
... 
0: a
1: b
2: c
```
</blockquote></details>

Done.
___
*[`bin/annotation/compare_annotation.py` line 192 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCLpJ19dVxsbiov2rG:-NoMuSUyDCpfUdCCgX29:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L192)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

calling `.strip()` on these would save the double checking of empty string or space below
</blockquote></details>

Done.
___
*[`bin/annotation/compare_annotation.py` line 247 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGwOX96wiywQcbgqK2:-NoMwthk69hFPmX1k4dd:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L247)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I'd add a check for the first element being '>' - if it isn't you know something has gone really wrong and can throw an error
</blockquote></details>

Done.
___
*[`bin/annotation/compare_annotation.py` line 277 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGvEBj3Z_mZ1fyMH8m:-NoMxYXVApGKRPNJ8dw4:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L277)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I'd put the columns you use over and over again in a list at the top of make_dataframes. Then you can pass the list to 'columns' when you make DataFrames.
It's generally safer to do this for variables you're reusing a lot. Less risk of a copy-paste mistake causing weird problems later.
</blockquote></details>

Done.
___
*[`bin/annotation/com [...]

2024-01-19 15:41 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 12 of 38 files reviewed, 73 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/util/utils.py` line 378 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCD17I5pBRAjzL5eWh:-NoXKMme4BTAcvqMEKd8:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L378)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

input missing from docstring
</blockquote></details>

Done.
___
*[`bin/util/utils.py` line 400 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCD3R-5uIeI9cbiQVQ:-NoXKOmh6tyV_TZaApX4:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L400)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

inputs missing from docstring
</blockquote></details>

Done.
___
*[`bin/util/vep_testing.py` line 33 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGjUimDyUlpRlUEgDe:-NoXKfGX01P9isoP5C6I:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L33)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please check every one of your docstrings before the next review round. You seem to be missing args from many of them.
</blockquote></details>

Done.
___
*[`bin/util/vep_testing.py` line 308 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGg9ob3vvOBA5nm7Fj:-NoXKsGx8B99td_30Q3U:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L308)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Explain the args 'ref_proj_id' and 'genome_build' too please.
Ideally also specify the argument and return types, if it's a newish version of Python. 
That would look like this:
</blockquote></details>

Done.
___
*[`bin/vep_config/vep_config_update.py` line 201 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoH1Jq64ZIWgMWgYubD:-NoXL4DVEQaJW1F-QlB-:bxi5hty) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/vep_config/vep_config_update.py#L201)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

what's the next step if pr is not merged, is it manual intervention?
</blockquote></details>

If the PR is not merged already, step 1 will be run. Failing this step implies either an internal error of Prometheus, or an error with the github API. Manual intervention will always result in a slack notification prompting the team to check on any failed tests
___
*[`bin/vep_config/vep_config_update.py` line 353 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoH2Y0RC_k821kRHVm6:-NoXNHfJEvLncSV9quJq:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/vep_config/vep_config_update.py#L353)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

docstring on what args are required and example cmd
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-22 15:52 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 9 of 38 files reviewed, 73 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/tests/test_compare_annotation.py` line 11 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGlln33Kh9ewDdGX_C:-NolrOSi3_VvnemmAsa1:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L11)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Give this a more informative name than testCase. TestCompareAnnotations maybe
</blockquote></details>

Done.
___
*[`bin/tests/test_compare_annotation.py` line 13 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCZYu0DMc_r5bBlCmf:-NolrRQ6EHiFXPRz-XhZ:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L13)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

docstring on what this is testing and expectation. same for other unit test functions
</blockquote></details>

Done.
___
*[`bin/tests/test_compare_annotation.py` line 130 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_F-h1TNeRT3McTnF:-NolrTuyA2Hh-kFKGICo:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L130)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/tests/test_compare_annotation.py` line 138 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_Hf5CPmM3tx7y1lb:-NolrUls6v8Qmy1xCYZi:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L138)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/tests/test_inspect_vep_logs.py` line 9 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_NMk9mCVxw3fhjHe:-NolrVbHEpauJhqTMltL:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_inspect_vep_logs.py#L9)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/tests/test_progress_tracker.py` line 13 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGuZwABlcf81i2H9xx:-NolrZt4-Tx7oXwOmHSE:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_progress_tracker.py#L13)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please use a more informative name for your testCase!
</blockquote></details>

Done.
___
*[`bin/tests/test_vep_testing.py` line 39 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCauKe8vnYMrsOfZhv:-Nolr_uuCNDDtrGVQprC:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_vep_testing.py#L39)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`bin/tests/test_vep_testing.py` line 55 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGfpSiBMqY9AJT6-fj:-Nolrb-zESBucO2ovoXl:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_vep_testing.py#L55)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Docstring here too (and anywhere else in the tests that's missing one). Please always explain what you're trying to test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-23 14:09 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 9 of 38 files reviewed, 73 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/tests/test_login_handler.py` line 20 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_yNNBtMvBXDac09x:-NopzX5L1-K9EtqkkzeB:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_login_handler.py#L20)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

i see that login_handler raise exception if dnanexus login with token failed. the unit test should test for exception raised instead
</blockquote></details>

Done.
___
*[`bin/annotation/get_clinvar_files.py` line 94 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCN5EnCqO_21sah428:-Noppm879HT-TfRJTZ6M:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/get_clinvar_files.py#L94)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think these base URLs would be better in the config to make it easier to fix if they change the hosting end point
</blockquote></details>

Done.
___
*[`bin/util/utils.py` line 18 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC3wKBCDwdV5TF0lTt:-Noq6c1M3Yxsk-BUqp-X:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L18)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this function being called to just wait until some vep job / workflow completes? If so, dxpy already has a built in method for this for both DXJob and DXAnalysis which is `wait_on_done()`, you can just loop over your given IDs and call it and it will hold your app until they all complete (or if any error or timeout).

Example usage of it: https://github.com/eastgenomics/eggd_conductor/blob/297ce91c2cadfa42b9a7afe341ecad00010ea02b/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L1269
</blockquote></details>

Done.
___
*[`bin/util/utils.py` line 61 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC4Q906tx0AEEDpIK_:-Noq6fLUE14IuYolqT39:b2d8m3g) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L61)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

shouldn't need a separate function from above, just use `dxpy.DXJob` or `DXAnalysis` dependent on the specified ID
</blockquote></details>

Done. Removed the function as it is no longer needed
___
*[`bin/util/utils.py` line 190 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC63-n0d8Q5W_osegH:-NoqG9Xj4lSQPivWP-LE:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L190)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

instead of calling `.describe()` on every file, when you do `dxpy.find_data_objects()` you can specify `describe=True` which will return the describe output directly in a single query, which is much faster
</blockquote></details>

Done.
___
*[`bin/util/utils.py` line 275 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC8pJJ1WmDATOK81gt:-Noq7wcH0TB3AYr9nXaS:b-pmz5mw) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L275)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why would the folder path be an empty string (sorry I don't know the context of the function being called)?

since `dxpy.find_data_objects` defaults inputs to `None`, I'd just assign  `folder_path` to None if its being passed as an empty string (or switch to providing None to this function), then the if else duplicating the dxpy call can be removed

one liner for setting it to `None` if you need:
```
folder_path = None if folder_path == '' else folder_path
```
</blockquote></details>

Done. It would be an empty string if you want to search the project root folder
___
*[`bin/util/utils.py` line 334 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCCs-W7nm9ad5Kdnty:-NoqCem_Aa8a5xLT6JBy:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L334)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above with simplifying the call by switching `folder_path` to `None`
</blockquote></details>

Done.
___
*[`bin/util/utils.py` line 368 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCCg2TD66Qsr4D4ZPt:-NoqChAwC7Ry95QU6nsz:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L368)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this comment copy pasted? I'd consider refactoring this with above, and adding a boolean of `return_latest` or `return_all` to control what is returned since they're doing nearly the same thing
</blockquote></details>

Done.
___
*[`bin/util/utils.py` line 415 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCD7-M6WSKeDlqPgMF:-NoqMVTpDQaI_BKioQw3:b3hss53) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L415)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if assay is not in those 3 you will get a `NameError` on the return as the repo variable won't be defined, do we need to handle this?
</blockquote></details>

Handled
___
*[`bin/util/utils.py` line 523 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCJ-DZ4qLpgaYxnc-1:-NoqalX31jXgNDOPqze-:btr6yoh) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L523)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what's the requirement of this function? is it always called before the one above to replace, and if so can they just be combined?
</blockquote></details>

No, the two functions are independent. This finds a string in a json file from a regex provided
___
*[`bin/util/vep_testing.py` line 53 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGwJKi4znya6IMqc2P:-NoqcLw17Vxu6ONJI5FE:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L53)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

try clause if dxid or project is invalid
</blockquote></details>

Done.
___
*[`bin/util/vep_testing.py` line 202 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGxWFq8wPNb_WaXo7_:-NoqZynRBT5LO7Tpa-Cx:be2svuk) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L202)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

is there a chance this won't split() into list of 5 values?
</blockquote></details>

It will always split to 5 unless the format of the input vcf is invalid. I've added a check just in case


<!-- Sent from Reviewable.io -->

2024-01-23 15:58 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 9 of 38 files reviewed, 73 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/util/utils.py` line 257 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC7_2I-nwoGzxXZhTr:-Noqtzfw1FJJFgNCxlce:b-g74nff) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L257)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

in this scenario, if a file was created in a 004 project for a major version change (i.e. 1.3.0 -> 1.4.0), but in the time of testing and deploying a minor hotfix version was created and deployed (i.e. 1.3.0 -> 1.3.1), the 1.3.1 version would then always have a newer created date wouldn't it? I assume created date is unchanged on copying to 001_Reference since (I think) it relates to the file object and not just that file object in the project context
</blockquote></details>

Done. Replaced with parsing the version then selecting the latest version by file name
___
*[`bin/util/utils.py` line 317 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCCUi4AtDtDqtnMPug:-NoqtgXS85UO5sAD1I9K:bu5lah4) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L317)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same comment as above for `get_prod_vep_config()`
</blockquote></details>

This shouldn't be an issue for find_dx_file(), as it's intended to return the latest file created


<!-- Sent from Reviewable.io -->

2024-01-23 16:14 UTC, corbin-chris requested changes
> Reviewed 1 of 21 files at r5, 1 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 11 of 38 files reviewed, 69 unresolved discussions (waiting on @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`bin/tests/test_compare_annotation.py` line 86 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGlyDjEOkQXDo_IZUt:-NopvRbWDF5RWUalI66b:b-urpj2o) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L86)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Thanks. I meant to look into this earlier but never got around to it. That seems a lot simpler than relying on the file system
</blockquote></details>

I definitely recommend it but I'll leave it up to you/others on the project to decide whether it's worth the rewrite time
___
*[`bin/tests/test_get_clinvar_files.py` line 16 at r15](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoqzTgc1DkaJXK_bQSV:-NoqzTgc1DkaJXK_bQSW:b-ubasqs) ([raw file](https://github.com/eastgenomics/prometheus/blob/4be823a89d20da26b2efeb2b5124a234ae93a701/bin/tests/test_get_clinvar_files.py#L16)):*
> ```Python
>         """test connect_to_website can connect to website
>         """
>         assert type(gc.connect_to_website()) is ftplib.FTP
> ```

To the best of your ability, you should mock out any calls to APIs/web resources in your unit tests.
Otherwise they won't run if the API is down or if you're offline (and you can spam them to death by accident). 
For an example, see 'test_get_specific_version_panel.py' on the main branch of Eris - mock.patch is used to replace 'requests.get' with some return data saved in a JSON file, and also a fake status code.
___
*[`bin/tests/test_make_vep_test_configs.py` line 10 at r10](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nopu-DQ5IgFBOyeoWDN:-Nopu-DQ5IgFBOyeoWDO:b5o783b) ([raw file](https://github.com/eastgenomics/prometheus/blob/f6e02c499c2668793d227b68ff8e209a9debb244/bin/tests/test_make_vep_test_configs.py#L10)):*
> ```Python
> 
> 
> class testMakeVepTestCOnfigs(unittest.TestCase):
> ```

Spare capital 'o' here
___
*[`bin/annotation/compare_annotation.py` line 499 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGsCiu5EfnaexuUUvl:-NopugPr3wO6_hajpfTF:bspyck5) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/annotation/compare_annotation.py#L499)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Done. I only made them variables so they could fit in 80 character lines for pep8
</blockquote></details>

If you want to meet pep8, it's probably better to split your conflict line dictionary across lines, rather than make extra variables. However, I'm a chronic line-length disrespecter because I auto-format with black, so I'm not a good example.
___
*[`bin/annotation/compare_annotation.py` line 282 at r10](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NopxjEU1MM926TB42Pg:-NopxjEV5UKK8okYykkQ:b-c2vyd0) ([raw file](https://github.com/eastgenomics/prometheus/blob/f6e02c499c2668793d227b68ff8e209a9debb244/bin/annotation/compare_annotation.py#L282)):*
> ```Python
> 
>     Returns:
>         added_df: pandas.DataFrame
> ```

This 'returns' list in the docstring is out-of-date. You still return added_df, but you also now return deleted_df, changed_df, detailed_df as well, so please add lines for them.
___
*[`bin/annotation/compare_annotation.py` line 305 at r10](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nopy8kyDw4GMgIib3Aa:-Nopy8kyDw4GMgIib3Ab:bvalwst) ([raw file](https://github.com/eastgenomics/prometheus/blob/f6e02c499c2668793d227b68ff8e209a9debb244/bin/annotation/compare_annotation.py#L305)):*
> ```Python
>     deleted_df = pandas.DataFrame(
>         data=deleted_list, columns=[
>             "mutation", "clinvar ID", "category", "info"
> ```

This should be 



_Code snippet:_
```Python
columns=standard_cols
```
___
*[`bin/annotation/compare_annotation.py` line 383 at r10](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nopyc_F6sJhV0E3Yrvy:-Nopyc_F6sJhV0E3Yrvz:b41omwn) ([raw file](https://github.com/eastgenomics/prometheus/blob/f6e02c499c2668793d227b68ff8e209a9debb244/bin/annotation/compare_annotation.py#L383)):*
> ```Python
>         "pathogenic_prod", "pathogenic_dev",
>         "path_low_penetrance_prod", "path_low_penetrance_dev",
>         "unknown_prod", "unknown_dev"
> ```

Repeated list - could you please define this once and then pass to both detailed_df and evidence_df?
You might be able to use it in the initial set-up of evidence_df too - I can't tell, because the very long repeated code is obscuring what the code is meant to be for. 



_Code snippet:_
```Python
very_long_col_name_list = ["my", "cols", "here"]
detailed_df[very_long_col_name_list] = evidence_df[very_long_col_name_list]
```
___
*[`bin/util/vep_testing.py` line 308 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGg9ob3vvOBA5nm7Fj:-NopwRBUD1h-POS6uW8H:b29ej01) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L308)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You want square brackets rather than round ones for: 



_Code snippet:_
```Python
) -> tuple[str, str]
```


<!-- Sent from Reviewable.io -->

2024-01-26 15:39 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 11 of 38 files reviewed, 69 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/tests/test_get_clinvar_files.py` line 16 at r15](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoqzTgc1DkaJXK_bQSV:-Np5MCuJArsbsUT1n4CP:b-713s0t) ([raw file](https://github.com/eastgenomics/prometheus/blob/4be823a89d20da26b2efeb2b5124a234ae93a701/bin/tests/test_get_clinvar_files.py#L16)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

To the best of your ability, you should mock out any calls to APIs/web resources in your unit tests.
Otherwise they won't run if the API is down or if you're offline (and you can spam them to death by accident). 
For an example, see 'test_get_specific_version_panel.py' on the main branch of Eris - mock.patch is used to replace 'requests.get' with some return data saved in a JSON file, and also a fake status code.
</blockquote></details>

I'll keep reading up on unittest.mock and try to implement it here 
___
*[`bin/tests/test_make_vep_test_configs.py` line 10 at r10](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nopu-DQ5IgFBOyeoWDN:-Np4a-NcC8mQbU6VOw3v:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/f6e02c499c2668793d227b68ff8e209a9debb244/bin/tests/test_make_vep_test_configs.py#L10)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Spare capital 'o' here
</blockquote></details>

Done.
___
*[`bin/annotation/compare_annotation.py` line 282 at r10](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NopxjEU1MM926TB42Pg:-Np4aX2N0LJadP1jTBPL:bmbzdrb) ([raw file](https://github.com/eastgenomics/prometheus/blob/f6e02c499c2668793d227b68ff8e209a9debb244/bin/annotation/compare_annotation.py#L282)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

This 'returns' list in the docstring is out-of-date. You still return added_df, but you also now return deleted_df, changed_df, detailed_df as well, so please add lines for them.
</blockquote></details>

All of the other returns are listed below 'added_df'. Maybe you were looking at an older version of the docstring?
___
*[`bin/annotation/compare_annotation.py` line 305 at r10](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nopy8kyDw4GMgIib3Aa:-Np4ZI1J-O1rHsAsMtiu:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/f6e02c499c2668793d227b68ff8e209a9debb244/bin/annotation/compare_annotation.py#L305)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

This should be
</blockquote></details>

Done.
___
*[`bin/annotation/compare_annotation.py` line 383 at r10](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nopyc_F6sJhV0E3Yrvy:-Np4ZhouBdcnV38XGh67:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/f6e02c499c2668793d227b68ff8e209a9debb244/bin/annotation/compare_annotation.py#L383)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Repeated list - could you please define this once and then pass to both detailed_df and evidence_df?
You might be able to use it in the initial set-up of evidence_df too - I can't tell, because the very long repeated code is obscuring what the code is meant to be for.
</blockquote></details>

Done.
___
*[`bin/util/vep_testing.py` line 308 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGg9ob3vvOBA5nm7Fj:-Np4a9qt06uqeLwuCXNc:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L308)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You want square brackets rather than round ones for:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-29 13:42 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 10 of 38 files reviewed, 69 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/tests/test_get_clinvar_files.py` line 16 at r15](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoqzTgc1DkaJXK_bQSV:-NpKRCit2KBwTAxY9ku_:b-ebmjo2) ([raw file](https://github.com/eastgenomics/prometheus/blob/4be823a89d20da26b2efeb2b5124a234ae93a701/bin/tests/test_get_clinvar_files.py#L16)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

I'll keep reading up on unittest.mock and try to implement it here
</blockquote></details>

I've read through the eris code you mentioned and some unittest mock guides. I've patched over two of the calls in test_connect_to_website, so that test should be safe to run without making any API calls. However, "ftp.retrlines('LIST', file_list.append)" from the test "test_get_ftp_files" seemed difficult to patch over. Would you like me to remove the unit test for now, or keep it as is?


<!-- Sent from Reviewable.io -->

2024-01-30 11:27 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 10 of 38 files reviewed, 69 unresolved discussions (waiting on @corbin-chris, @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`bin/util/utils.py` line 437 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoCEeXYDd9yZnwUAshV:-NpKT9FN7ujvl0_WAxfJ:b6gh8cu) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/utils.py#L437)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you provide an example of the file structure you're parsing through here, and what the `first_match` parameter would be expected to be? Parsing through JSON line by line I think would be better reading it in with `json.loads()` and then if you're only wanting to modify values in some arbitrarily nested structure, I'd consider using something like `flatten-dict` to make you life easier (and also makes sure you're only modifying values in the json).

```
from flatten_dict import flatten, unflatten

>>> conf = {'foo1': {'bar1': {'baz1': 'blarg1'}}, 'foo2': {'bar1': 'baz2'}} 
>>> flat = flatten(conf)
>>> flat
{('foo1', 'bar1', 'baz1'): 'blarg1', ('foo2', 'bar1'): 'baz2'}


>>> flat = {k: re.sub(r'blarg1', 'new_string', v) for k, v in flat.items()}
>>> flat
{('foo1', 'bar1', 'baz1'): 'new_string', ('foo2', 'bar1'): 'baz2'}
>>> unflatten(flat)
{'foo1': {'bar1': {'baz1': 'new_string'}}, 'foo2': {'bar1': 'baz2'}}
```

This allows us to call the `re.sub()` only on the values and ensure we rebuild it as a valid JSON dumpable structure.

If you're then wanting to only use the regex on a subsection, you could either select that part from the dict and do the above, or check that your given string is in the path to the value (i.e. the flattened keys)

https://pypi.org/project/flatten-dict/
</blockquote></details>

The first_match parameter was a way of finding a unique string before the string to be replaced.
Example json file structure below. In this example, if I wanted to modify the line '"file_id":"CLINVAR_VCF_FILE_ID"' I would input '"resource_files": [' as the parameter first_match. The function would find the unique string '"resource_files": [', then assume the next line matching the parameter replace_regex is the desired match. I added the check for first_match in case there were multiple potential matches for replace_regex.

I have updated the functions to use json.load and flatten.



_Code snippet:_
```Python
{
  "config_information":{
    "genome_build": "GRCh37"
  },
  "vep_resources":{
    "vep_docker":"file-G8V2Vz0433Gp5bYPF2f6vg9X",
    "vep_cache":"file-G8V4bGj433Gz96K3Fb1VfbG3",
    "reference_fasta":"file-G6BYyyj4YV3pYBkgFVGP2K4P",
    "reference_fai":"file-G6P32kj4YV3y58KyP4k4qG2p",
    "reference_gzi":"file-G6BYz104YV3X5qp463K5b5vp",
    "ref_bcftools":"file-F3zxG0Q4fXX9YFjP1v5jK9jf"
  },
  "custom_annotations": [
    {
      "name": "ClinVar",
      "type": "vcf",
      "annotation_type": "exact",
      "force_coordinates": "0",
      "vcf_fields": "CLNSIG,CLNREVSTAT,CLNDN,CLNSIGCONF",
      "required_fields":"ClinVar,ClinVar_CLNSIG,ClinVar_CLNSIGCONF,ClinVar_CLNDN",
      "resource_files": [
        {
          "file_id":"CLINVAR_VCF_FILE_ID",
          "index_id":"CLINVAR_VCF_TBI_FILE_ID"
        }
      ]
    }
  ],
  "plugins": [
  ],
  "additional_fields":[
    "Consequence",
    "Feature"
  ]
}
```


<!-- Sent from Reviewable.io -->

2024-02-22 10:01 UTC, corbin-chris requested changes
> Reviewed 2 of 30 files at r17.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 8 of 48 files reviewed, 65 unresolved discussions (waiting on @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`bin/tests/test_get_clinvar_files.py` line 16 at r15](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoqzTgc1DkaJXK_bQSV:-NrFEX0nBfCvULeCcQZG:b32gazn) ([raw file](https://github.com/eastgenomics/prometheus/blob/4be823a89d20da26b2efeb2b5124a234ae93a701/bin/tests/test_get_clinvar_files.py#L16)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

I've read through the eris code you mentioned and some unittest mock guides. I've patched over two of the calls in test_connect_to_website, so that test should be safe to run without making any API calls. However, "ftp.retrlines('LIST', file_list.append)" from the test "test_get_ftp_files" seemed difficult to patch over. Would you like me to remove the unit test for now, or keep it as is?
</blockquote></details>

Please don't just skip tests because they're difficult to write.
Did you move the test to another file? Files have deleted/moved and it has made the Reviewable view a bit weird.
If you're still struggling with it, Slack message me with more code snippets and background, I'll see if I can get some of the mocking working.
Worst case scenario, we'll check what's here already, but do another smaller PR to 'clean up' missing tests before approving.
___
*[`tests/test_compare_annotation.py` line 134 at r17](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nqccu8FAPXQebLOSyum:-Nqccu8FAPXQebLOSyun:b-unhjso) ([raw file](https://github.com/eastgenomics/prometheus/blob/689a2ada6cde4a799a46cee310bc38bcdcd031a4/tests/test_compare_annotation.py#L134)):*
> ```Python
> 
>     def test_regex_conflicting_other_invalid(self):
>         """test that get_full_categoty_name fails when conflicting other
> ```

Typo 'categoty' instead of 'category'


<!-- Sent from Reviewable.io -->

2024-02-22 11:21 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 8 of 48 files reviewed, 64 unresolved discussions (waiting on @corbin-chris, @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`bin/tests/test_get_clinvar_files.py` line 16 at r15](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoqzTgc1DkaJXK_bQSV:-NrFWjy96i4MjAxexKcJ:b-onug2o) ([raw file](https://github.com/eastgenomics/prometheus/blob/4be823a89d20da26b2efeb2b5124a234ae93a701/bin/tests/test_get_clinvar_files.py#L16)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please don't just skip tests because they're difficult to write.
Did you move the test to another file? Files have deleted/moved and it has made the Reviewable view a bit weird.
If you're still struggling with it, Slack message me with more code snippets and background, I'll see if I can get some of the mocking working.
Worst case scenario, we'll check what's here already, but do another smaller PR to 'clean up' missing tests before approving.
</blockquote></details>

The removed file had a single unit test, so the file was removed with the unit test. I'll message you over slack to explain why it's a complex case to patch over


<!-- Sent from Reviewable.io -->

2024-02-22 16:55 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 8 of 48 files reviewed, 65 unresolved discussions (waiting on @corbin-chris, @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`bin/resources/template_VEP_Config.json` line 6 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrGjSPjC7X53fBtnSwS:-NrGjSPjC7X53fBtnSwT:bohep37) ([raw file](https://github.com/eastgenomics/prometheus/blob/ac1762166e470b6237b5ace4f73c98b26d37bb82/bin/resources/template_VEP_Config.json#L6)):*
> ```JSON
>   },
>   "vep_resources":{
>     "vep_docker":"file-G8V2Vz0433Gp5bYPF2f6vg9X",
> ```

If we update the VEP docker/cache in the config would that break prometheus or require an update to this template?


<!-- Sent from Reviewable.io -->

2024-02-22 16:59 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 8 of 48 files reviewed, 65 unresolved discussions (waiting on @corbin-chris, @JasonLing95, @jethror1, and @RSWilson1)

___
*[`bin/resources/template_VEP_Config.json` line 6 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrGjSPjC7X53fBtnSwS:-NrGjwBvARwr7bJPk9Pr:b-e2res7) ([raw file](https://github.com/eastgenomics/prometheus/blob/ac1762166e470b6237b5ace4f73c98b26d37bb82/bin/resources/template_VEP_Config.json#L6)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

If we update the VEP docker/cache in the config would that break prometheus or require an update to this template?
</blockquote></details>

Yes, I think I'd need to update the template. However, after today's discussion it seems that downloading from the latest github release and editing the file contents would be a lot more robust. That way I could avoid the problem of changes to the template entirely


<!-- Sent from Reviewable.io -->

2024-02-22 19:29 UTC, corbin-chris requested changes
> Reviewed 6 of 30 files at r17, 9 of 15 files at r18, 2 of 4 files at r19, all commit messages.
> Dismissed @JasonLing95 from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 25 of 48 files reviewed, 77 unresolved discussions (waiting on @JasonLing95, @jethror1, @PolarisAstrum-NHS, and @RSWilson1)

___
*[`bin/tests/test_get_clinvar_files.py` line 16 at r15](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoqzTgc1DkaJXK_bQSV:-NrHHThNBM72BBJYLvH4:bflgn43) ([raw file](https://github.com/eastgenomics/prometheus/blob/4be823a89d20da26b2efeb2b5124a234ae93a701/bin/tests/test_get_clinvar_files.py#L16)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

The removed file had a single unit test, so the file was removed with the unit test. I'll message you over slack to explain why it's a complex case to patch over
</blockquote></details>

Done we discussed this and I have made new requests/comments based on it
___
*[`bin/tests/test_make_vep_test_configs.py` line 0 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH1--776kkA12Ph-kP:-NrH1--776kkA12Ph-kQ:b-fytfec) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/tests/test_make_vep_test_configs.py#L0)):*
You still need to test def generate\_config\_files
Is dxpy mocking the trouble here? @jethror1 knows more about that than me I think
___
*[`tests/test_get_clinvar_files.py` line 16 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH015kDZdlKkEJzoBj:-NrH015kDZdlKkEJzoBk:b-8x8o4i) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_get_clinvar_files.py#L16)):*
> ```Python
>         link = "https://ftp.ncbi.nlm.nih.gov"
>         path = "/path/to/file"
>         assert type(gc.connect_to_website(link, path, "b37")) is ftplib.FTP
> ```

Be sure to test the cases where you get errors/error messages too, with self.assertRaisesRegex() - I put an example on this review somewhere
A few functions aren't tested yet in 'get_clinvar_files.py' but we've been discussing some approaches in Slack so I won't rehash them here.
___
*[`tests/test_progress_tracker.py` line 29 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH27435uiar6lG80EG:-NrH27435uiar6lG80EH:bedc4na) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_progress_tracker.py#L29)):*
> ```Python
>         Mock(return_value=None)
>     )
>     def test_perform_checks(self):
> ```

You still need to add tests for the second half of this function.
Most functions on this page still need tests.



_Code snippet:_
```Python
self.check_configs_made() 

        if not self.configs_made: 

            return 

        self.check_evidence_uploaded() 

        if not self.evidence_uploaded: 

            return 

        self.check_changes_status() 

        if self.changes_status == self.STATUS_UNCHECKED: 

            return 

        self.check_clinvar_deployed() 
```
___
*[`tests/test_utils.py` line 1 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH2bSK3r49OWzWxyfT:-NrH2bSK3r49OWzWxyfU:bi0lsq9) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L1)):*
> ```Python
> import unittest
> ```

Half the functions on utils.py don't have tests yet according to your coverage report, please check them and ask for help if you need to e.g. mock something tricky
Same for vep_testing.py (though again for dx @jethror1 has experience and I don't)
___
*[`bin/vep_config_update.py` line 93 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH41hMARUZTkpi__wo:-NrH41hMARUZTkpi__wp:b-5i8d1e) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/vep_config_update.py#L93)):*
> ```Python
>     # merge pull request to main branch
>     split_assay_url = assay_repo.split("/")
>     repo_name = f"{split_assay_url[3]}/{split_assay_url[4]}"
> ```

Is it possible to do some regex-matching, to catch any cases where the assay repo has been incorrectly named? (If this is ever a possibility)
___
*[`bin/vep_config_update.py` line 117 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH8YBAB8pRwV_ag5af:-NrH8YBAB8pRwV_ag5ag:b7b1r6n) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/vep_config_update.py#L117)):*
> ```Python
>             exit_prometheus()
> 
>         is_different = is_vep_config_id_different(
> ```

To reduce a bit of string repetition - would it be possible to set up 'is_vep_config_id_different' so that it also takes the string "vcf index id" or "vcf id" as an argument, e.g. file_type?
Then, you could set up the error_message inside 'is_vep_config_different' by swapping in that string like so:
f "Error: The ClinVar {file_type} in the current"
                + " VEP config is identical to the new ClinVar"
                + f" {file_type} {vcf_or_index_id}. Therefore, this"
                + " config file does not need to be updated"
            )
And then 'is_vep_config_id_different' could return two values, 'is_different' and 'error_message', with the second only getting used if 'is_different' is False.
___
*[`bin/vep_config_update.py` line 130 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH67Kw8tUAr8EP6HVr:-NrH67Kw8tUAr8EP6HVs:bihwvjz) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/vep_config_update.py#L130)):*
> ```Python
>             exit_prometheus()
> 
>         # switch to new branch
> ```

run_vep_config_update would benefit from having a lot of its code refactored into smaller functions, which run_vep_config_update then calls. Even if a lot of these functions don't get reused, this will make it much easier to read, and probably to unit test. Currently run_vep_config_update doesn't have any code coverage. It it's just coordinating a few functions that's OK, but it's 300 lines containing most of the application logic, which gets a bit hairy.

The 'switch to new branch' section of code, or perhaps the section in the 'for file in repo_files' section, are good examples of a chunk of code which does approximately 1 overall thing and could merit a function. 
___
*[`bin/annotation/compare_annotation.py` line 353 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrHFaZlDY4HIq_wWcDN:-NrHFaZlDY4HIq_wWcDO:bzwr06) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/annotation/compare_annotation.py#L353)):*
> ```Python
>         evidence_list.append(all_evidence)
> 
>     # TODO: handle case for only evidence count changing (e.g., (1) to (2))
> ```

Have you address this todo yet or is it still waiting?
___
*[`bin/annotation/get_clinvar_files.py` line 40 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrHG_4eCCeY-I2Y-1dH:-NrHG_4eCCeY-I2Y-1dI:b-vbwbe0) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/annotation/get_clinvar_files.py#L40)):*
> ```Python
>     ftp.retrlines('LIST', file_list.append)
> 
>     latest_time = datetime.strptime("20200101", '%Y%m%d').date()
> ```

Should latest time be hardcoded here? Might it need to change in future, in which case, a config file setting or something else might be best? Otherwise if ClinVar updates your code will need updating too!
___
*[`bin/tests/test_compare_annotation.py` line 130 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoC_F-h1TNeRT3McTnF:-NrGz_GGBCPX3XgnrVeH:bb6un1j) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/tests/test_compare_annotation.py#L130)):*
<details><summary><i>Previously, PolarisAstrum-N [...]

2024-02-23 08:32 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 25 of 48 files reviewed, 76 unresolved discussions (waiting on @corbin-chris, @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`bin/resources/template_VEP_Config.json` line 6 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrGjSPjC7X53fBtnSwS:-NrK4wRZ6xmUdteMW9Ro:bkfyucy) ([raw file](https://github.com/eastgenomics/prometheus/blob/ac1762166e470b6237b5ace4f73c98b26d37bb82/bin/resources/template_VEP_Config.json#L6)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Yes, I think I'd need to update the template. However, after today's discussion it seems that downloading from the latest github release and editing the file contents would be a lot more robust. That way I could avoid the problem of changes to the template entirely
</blockquote></details>

Yeah that sounds like a good plan!


<!-- Sent from Reviewable.io -->

2024-02-23 12:52 UTC, corbin-chris requested changes
> Reviewed 1 of 16 files at r3, 3 of 19 files at r4, 1 of 21 files at r5, 1 of 13 files at r8, 11 of 30 files at r17, 4 of 15 files at r18, 2 of 4 files at r19.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: all files reviewed, 108 unresolved discussions (waiting on @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`tests/test_login_handler.py` line 37 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKvani67JNzh7vNF4I:-NrKvani67JNzh7vNF4J:bll6033) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_login_handler.py#L37)):*
> ```Python
>             Mock(return_value=("dx_token", "slack_token"))
>     )
>     def test_load_credentials(self):
> ```

I can't see it on this reviewable, but load_credentials takes bin_folder as an input, and it isn't used.
So you might want to edit load_credentials to remove bin_folder that as an argument
___
*[`tests/test_login_handler.py` line 43 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKvwaU2A2P8a8o7H9g:-NrKvwaU2A2P8a8o7H9h:buwcblq) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_login_handler.py#L43)):*
> ```Python
>         with patch(
>             "bin.util.login_handler.LoginHandler.load_credentials",
>             Mock(return_value=("invalid_token", "", ""))
> ```

Is invalid_token here just a 'placeholder' for a token which would work in real life (and be returned by load_credentials)?
___
*[`tests/test_make_vep_test_configs.py` line 22 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKwOGO5-qGO9y2Y3Yv:-NrKwOGO5-qGO9y2Y3Yw:bk80ynv) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_make_vep_test_configs.py#L22)):*
> ```Python
>                     ""
>                 ) == output
>             )
> ```

Do you ever check that your final file has the correct stuff written to it? Hard to tell here
___
*[`tests/test_utils.py` line 15 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKxTH71YujlUSIacCF:-NrKxTH71YujlUSIacCG:b-6l9e4e) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L15)):*
> ```Python
> class testUtils(unittest.TestCase):
> 
>     def test_check_project_exists(self):
> ```

check_project_exists is used infrequently enough and is small enough that you could probably just call DXproject(project_id) directly in the spots where you use it (example in check_proj_folder_exists below), unless you're particularly invested in keeping DX stuff in utils only (but it doesn't look like that's the case). If you do want to keep it, you should mock out the call to DX when testing it, so you aren't really making dx calls.



_Code snippet:_
```Python
def check_proj_folder_exists(project_id, folder_path) -> bool:
    try:
        DXProject(project_id)
    except dxpy.exceptions.DXError:
        raise RuntimeError(f"Project {project_id} does not exist")
```
___
*[`tests/test_utils.py` line 50 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKyYuV-2IoQRMUVf0H:-NrKyYuV-2IoQRMUVf0I:b-ju5ich) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L50)):*
> ```Python
>     @patch("bin.util.utils.check_proj_folder_exists", Mock(return_value=True))
>     @patch("bin.util.utils.find_dx_file", Mock(return_value="test"))
>     def test_get_prod_version_valid(self):
> ```

Note that you still need to update  the Raises section of your docs for get_prod_vep_config
Right now it has Exception, should be RuntimeError
Check CTRL+F check your other 'Raises' sections for the same error please
___
*[`tests/test_utils.py` line 69 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKyw_WBTjVXLvf2eSf:-NrKyw_WBTjVXLvf2eSg:b-ghyvgp) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L69)):*
> ```Python
>         )
> 
>     def test_get_prod_version_invalid_project(self):
> ```

Again, you need to patch DX things here even if it's invalid input. You don't want it hitting the API at all if possible
___
*[`tests/test_utils.py` line 113 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKzFbTBdcWgWuDEUvE:-NrKzFbTBdcWgWuDEUvF:bkofer) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L113)):*
> ```Python
> 
>     @patch("builtins.open", mock_open(read_data="data"))
>     def test_load_config(self):
> ```

Your docstring for load_config has bin_path in it, please remove it as it doesn't get used
___
*[`tests/test_utils.py` line 131 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKzR4-7sP4GDVUHS8o:-NrKzR4-7sP4GDVUHS8p:beeg4rr) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L131)):*
> ```Python
>             ) = utils.load_config(bin_path, config_path)
>         assert (
>             ref_proj_id is not None
> ```

Separate lines again
___
*[`tests/test_utils.py` line 185 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKzcN9BjCzAKpVa2Li:-NrKzcN9BjCzAKpVa2Lj:b-vfjp8y) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L185)):*
> ```Python
>         ver = "1.1.1"
>         new_ver = utils.increment_version(ver)
>         assert new_ver == "1.1.2"
> ```

What happens if we need to denote a major release (e.g. 1.1.1 -> 1.2.1)? Or will those always be done manually rather than by Prometheus?
___
*[`tests/test_vep_testing.py` line 9 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL-BJ59SxNZtYbp6jw:-NrL-BJ59SxNZtYbp6jx:bhmky50) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L9)):*
> ```Python
> class testVepTesting(unittest.TestCase):
> 
>     # TODO: replace open for 2 different files
> ```

Still in progress?
___
*[`tests/test_vep_testing.py` line 31 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL-Xbi8k__ONwZEX-X:-NrL-Xbi8k__ONwZEX-Y:b-m2o3qj) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L31)):*
> ```Python
>         assert vt.get_diff_output(
>             "test_dev.txt", "test_prod.txt", "tso500", "bin"
>         ) == output
> ```

I want to see that the contents of the output match what you want too - right now you're just checking whether Python can string-concatenate to make your output file name.
___
*[`tests/test_vep_testing.py` line 44 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL-pyiCb8n9w-QU1Qj:-NrL-pyiCb8n9w-QU1Qk:bmxej3o) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L44)):*
> ```Python
>         assert vt.make_job_report(
>             dev_twe_job, dev_tso_job, prod_twe_job, prod_tso_job, output
>         ) == output
> ```

I want to see tests for this in failure states, e.g. when it has FileNotFoundError and FileExistsError
I'd also like tests for file contents rather than just file name (example shown earlier)
___
*[`tests/test_vep_testing.py` line 63 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL0Njz8KwHrkNJ-5Wt:-NrL0Njz8KwHrkNJ-5Wu:b-yw51jw) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L63)):*
> ```Python
>                 "name": "my_project",
>                 "created": "240101"
>             }
> ```

Can you put more projects in here, to check that the _most recent_ one is being fetched, rather than just a random one?
___
*[`bin/util/d [...]

2024-02-23 16:08 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: all files reviewed, 108 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/tests/test_make_vep_test_configs.py` line  at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH1--776kkA12Ph-kP:-NrKSC8wCvo09dEdB0LW:b-4cogra) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/tests/test_make_vep_test_configs.py#L)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You still need to test def generate\_config\_files
Is dxpy mocking the trouble here? @jethror1 knows more about that than me I think
</blockquote></details>

I need to mock a lot of local functions to make this one work. If we can get local function mocking working, I can add the unit test
___
*[`tests/test_login_handler.py` line 43 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKvwaU2A2P8a8o7H9g:-NrLTsDX7KMtVVAQsjk4:b2nhswy) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_login_handler.py#L43)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Is invalid_token here just a 'placeholder' for a token which would work in real life (and be returned by load_credentials)?
</blockquote></details>

Yes
___
*[`tests/test_utils.py` line 113 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKzFbTBdcWgWuDEUvE:-NrLVlG48HzhpX0qe3sc:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L113)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Your docstring for load_config has bin_path in it, please remove it as it doesn't get used
</blockquote></details>

Done.
___
*[`tests/test_utils.py` line 131 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKzR4-7sP4GDVUHS8o:-NrLWnrB7_jL9fV7mbUX:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L131)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Separate lines again
</blockquote></details>

Done.
___
*[`tests/test_utils.py` line 185 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKzcN9BjCzAKpVa2Li:-NrLWrhqEuAobhOerHqH:b-8fluvl) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L185)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

What happens if we need to denote a major release (e.g. 1.1.1 -> 1.2.1)? Or will those always be done manually rather than by Prometheus?
</blockquote></details>

Yes, those would be performed outside of Prometheus
___
*[`bin/vep_config_update.py` line 93 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH41hMARUZTkpi__wo:-NrKdcab6qSy1GRu22xl:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/vep_config_update.py#L93)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Is it possible to do some regex-matching, to catch any cases where the assay repo has been incorrectly named? (If this is ever a possibility)
</blockquote></details>

Done.
___
*[`bin/vep_config_update.py` line 117 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH8YBAB8pRwV_ag5af:-NrL7hedABftJshCL-On:b8ac7j5) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/vep_config_update.py#L117)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

To reduce a bit of string repetition - would it be possible to set up 'is_vep_config_id_different' so that it also takes the string "vcf index id" or "vcf id" as an argument, e.g. file_type?
Then, you could set up the error_message inside 'is_vep_config_different' by swapping in that string like so:
f "Error: The ClinVar {file_type} in the current"
                + " VEP config is identical to the new ClinVar"
                + f" {file_type} {vcf_or_index_id}. Therefore, this"
                + " config file does not need to be updated"
            )
And then 'is_vep_config_id_different' could return two values, 'is_different' and 'error_message', with the second only getting used if 'is_different' is False.
</blockquote></details>

Added function to send the slack message from a template
___
*[`bin/annotation/compare_annotation.py` line 353 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrHFaZlDY4HIq_wWcDN:-NrKQihS3ccIiyvryssI:bfmayuw) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/annotation/compare_annotation.py#L353)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Have you address this todo yet or is it still waiting?
</blockquote></details>

This todo is going to be a lot of work and isn't critical for generation of the evidence reports, so I was planning on adding this feature in a later version
___
*[`bin/annotation/get_clinvar_files.py` line 40 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrHG_4eCCeY-I2Y-1dH:-NrKR5TK8ZdAsJVk4cBh:b-48lugv) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/annotation/get_clinvar_files.py#L40)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Should latest time be hardcoded here? Might it need to change in future, in which case, a config file setting or something else might be best? Otherwise if ClinVar updates your code will need updating too!
</blockquote></details>

I picked this date as it will be earlier than anything we are updating now or in future, as a default value. This isn't something which needs to be updated
___
*[`bin/util/deployer.py` line 81 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKIPw89z2wd50lcbNK:-NrL8VUp61kxsVltar6Y:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/util/deployer.py#L81)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You could reduce code repetition here by looping over a list, after you've checked the project folder exists (See snippet).
In fact - you could reuse this function (with an updated name) for deploying your config file ID. Instead of passing a string of a DNAnexus ID, pass a list of strings of DNAnexus IDs. Then you can pass just [config] in a list, or pass [vcf_file_id, dev_project_id]
</blockquote></details>

Done.
___
*[`bin/util/deployer.py` line 125 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKKau26AYCaYRHqRlW:-NrL9wGK3Ax19TTYCOEV:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/util/deployer.py#L125)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You could reuse code in this big section by defining a dictionary-of-dictionaries up top:
file_id_dict = {"added_id": {"filename": added_csv} ... #and add in entries for "deleted_id" and so on as well

And then run uploads by looping over the dictionarr values, adding your IDs back to that first list, and finally return the dict instead of a tuple. When working with the results you could access the dictionary instead

HOWEVER - it looks like currently the returned dx ids aren't even used in your code? You return them but never refer to them in annotation_update.py If that's the case you don't even need a dictionary, you can just loop over a list of [added_csv, ...]
 [...]

2024-02-26 17:36 UTC, corbin-chris requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 37 of 48 files reviewed, 96 unresolved discussions (waiting on @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`bin/vep_config_update.py` line 97 at r20](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NraPpWo9ViFOVCzXkF3:-NraPpWo9ViFOVCzXkF4:bjj050s) ([raw file](https://github.com/eastgenomics/prometheus/blob/bb4febe1d3877c3acb0e1dc3069cf307a38a8982/bin/vep_config_update.py#L97)):*
> ```Python
>     if not re.match(assay_format, assay_repo):
>         error_message = (
>             f"Error: The assay repo {assay_repo} has bene incorectly formatted"
> ```

Tiny typos here ('bene' and 'incorectly')
___
*[`bin/annotation/get_clinvar_files.py` line 40 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrHG_4eCCeY-I2Y-1dH:-NraQuhs6jJNmOZcDncM:bhqw950) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/annotation/get_clinvar_files.py#L40)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

I picked this date as it will be earlier than anything we are updating now or in future, as a default value. This isn't something which needs to be updated
</blockquote></details>

In that case could you please rename it or change the param? Because the description in the param string is:
'version date of latest ClinVar file'
The 'latest' file usually means 'the most newly-available version of a file'. And when people talk about things that happened earlier in history, they say 'earlier'. You might want to rename the param to 'earliest_possible_date' instead?

You have a hardcoded 'latest_time' in two spots, get_clinvar_files and utils.py. Please define it in just 1 place and then import it or pass it as needed.
___
*[`bin/util/git_handler.py` line 96 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKNTWOCSKHmEkB3ttl:-NraSu_80DK80CaLd098:b-tsf6w0) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/util/git_handler.py#L96)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

This was a way of logically organising the code to be called by external functions. If Python had a privacy system, I would have made variables such as "self.repo" inaccessible to external functions. Things get messy very quickly otherwise
</blockquote></details>

Sure fine
___
*[`bin/util/vep_testing.py` line 14 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGvrqDA7npE4oaGm8Z:-NraTr-nCsrr__HHBcxU:b-r73ou7) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L14)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Removing "as compare_annotation" breaks the import
</blockquote></details>

Was this fixed when you sorted your other import issues? If yes I'll dismiss the comment.
___
*[`bin/vep_config/vep_config_update.py` line 13 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGy0yU3x4BaQw3SGeM:-NraP7Gg3QApjjsQ8rES:bb6un1j) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/vep_config/vep_config_update.py#L13)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Yes, it seems the other import fixes corrected the import error. "as vep_testing" has been removed
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-28 16:12 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 29 of 48 files reviewed, 87 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`tests/test_login_handler.py` line 37 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKvani67JNzh7vNF4I:-NrkE9O026913TzHa2_H:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_login_handler.py#L37)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I can't see it on this reviewable, but load_credentials takes bin_folder as an input, and it isn't used.
So you might want to edit load_credentials to remove bin_folder that as an argument
</blockquote></details>

Done.
___
*[`tests/test_make_vep_test_configs.py` line 22 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKwOGO5-qGO9y2Y3Yv:-NrkFhbIDWp291m_xvta:b-e9zojs) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_make_vep_test_configs.py#L22)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Do you ever check that your final file has the correct stuff written to it? Hard to tell here
</blockquote></details>

This just checks that the code executes successfully. Otherwise I'd need to use the file system
___
*[`bin/vep_config_update.py` line 97 at r20](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NraPpWo9ViFOVCzXkF3:-NrdbWnc4pQIKlH8uMQY:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/bb4febe1d3877c3acb0e1dc3069cf307a38a8982/bin/vep_config_update.py#L97)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Tiny typos here ('bene' and 'incorectly')
</blockquote></details>

Done.
___
*[`bin/annotation/get_clinvar_files.py` line 40 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrHG_4eCCeY-I2Y-1dH:-NrjXeJiA_1WQ-46eeSF:b-7v3vzc) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/annotation/get_clinvar_files.py#L40)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

In that case could you please rename it or change the param? Because the description in the param string is:
'version date of latest ClinVar file'
The 'latest' file usually means 'the most newly-available version of a file'. And when people talk about things that happened earlier in history, they say 'earlier'. You might want to rename the param to 'earliest_possible_date' instead?

You have a hardcoded 'latest_time' in two spots, get_clinvar_files and utils.py. Please define it in just 1 place and then import it or pass it as needed.
</blockquote></details>

The common meaning is the same as meaning I'm using. In this case, you can replace the word "latest" with "most recent" and I have to remove any possible ambiguity. To further clarify, setting the "latest_time" variable to an arbitrarily early date is analogous to setting the value to zero (i.e., the default value). This is to ensure that the variable "lastest_time" will always be less than the first date encountered in the list compared against in the line "if latest_time < date_object:"
___
*[`bin/util/vep_testing.py` line 14 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGvrqDA7npE4oaGm8Z:-Nrj_2H75j3GKqa-qGDz:bqokrdg) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/util/vep_testing.py#L14)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Was this fixed when you sorted your other import issues? If yes I'll dismiss the comment.
</blockquote></details>

Yes, solving the other import issues fixed this one
___
*[`bin/vep_config/vep_config_update.py` line 13 at r4](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NoGy0yU3x4BaQw3SGeM:-NrdbHCk0Dra-ct2-T-R:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/38d3de01ad015d9dd5a6af8b9003a3f869890e23/bin/vep_config/vep_config_update.py#L13)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.
___
*[`tests/test_compare_annotation.py` line 47 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH-8Qt9wWbCxgDNbGK:-NrjdV0p5xVMi_yso-CT:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_compare_annotation.py#L47)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

For get_full_category_name you need to write a test which covers these lines, checking that unknown_keys are appended correctly. Some of your Exception lines need covering too:
</blockquote></details>

Done.
___
*[`tests/test_compare_annotation.py` line 167 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrGs8b93fuoMxnJwrFV:-Nrjfxd-3neoSkFv5FTv:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_compare_annotation.py#L167)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you please add a test to cover this line, which is red in your coverage report?
Top snippet is the 'parse_diff()' line that needs testing. Bottom snippet is an example of some code that I think would test it for you - haven't tried it though. You might need to use side_effect to mimic the error, rather than return_data. 
assertRaisesRegex() lets you check that the error type and error message are correct at the same time.
</blockquote></details>

Done.
___
*[`tests/test_compare_annotation.py` line 223 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrGy9WL9Tk7wHeZT6Q9:-Nrjl-xi3-vZBy0C14HK:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_compare_annotation.py#L223)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You don't have a test to cover this line in split_variant_info at the moment: 'raise RuntimeError('
See my example of handling a RuntimeError to help you work out a test to cover it

Some other places where you throw RuntimeErrors are untested too - pick those up please
</blockquote></details>

Done.
___
*[`tests/test_slack_handler.py` line 17 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKwsNL24Ds5qycaiC_:-NrkTTR6EKK3miEyIpVC:b-ciqcbg) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_slack_handler.py#L17)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Are these TODOs still in progress?
</blockquote></details>

Yes and they have now been partially completed. However, I still need to find a way to patch over "requests.Session.post" without breaking the other patch
___
*[`tests/test_slack_handler.py` line 39 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKwyHv5hjj99haB9as:-NrkThn85wnobWWTjzYw:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_slack_handler.py#L39)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

And resurrect this test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-01 15:46 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 29 of 48 files reviewed, 87 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`tests/test_get_clinvar_files.py` line 16 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH015kDZdlKkEJzoBj:-Nru8anf7wgpoCvoYF1a:b-lv6fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_get_clinvar_files.py#L16)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Be sure to test the cases where you get errors/error messages too, with self.assertRaisesRegex() - I put an example on this review somewhere
A few functions aren't tested yet in 'get_clinvar_files.py' but we've been discussing some approaches in Slack so I won't rehash them here.
</blockquote></details>

I agree, this should be checked. However, in the interest of getting this PR resolved I think it's best to defer adding these checks until the next round of PR
___
*[`tests/test_progress_tracker.py` line 29 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH27435uiar6lG80EG:-NrtuRkvBkumJw9A-tds:b-vkbzxx) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_progress_tracker.py#L29)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You still need to add tests for the second half of this function.
Most functions on this page still need tests.
</blockquote></details>

Writing these unit tests is going to be very difficult due to mocks of local functions still causing problems. These additions seem out of scope for this PR and will be added in the next PR
___
*[`tests/test_utils.py` line 1 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH2bSK3r49OWzWxyfT:-Nrtuwh-EuEZDIvcq9XG:bdsewe0) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L1)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Half the functions on utils.py don't have tests yet according to your coverage report, please check them and ask for help if you need to e.g. mock something tricky
Same for vep_testing.py (though again for dx @jethror1 has experience and I don't)
</blockquote></details>

Out of scope for current PR, will be covered in the next one
___
*[`tests/test_utils.py` line 15 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKxTH71YujlUSIacCF:-NrtyXXqCYAZ6x9UQCq5:b-b7hum1) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L15)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

check_project_exists is used infrequently enough and is small enough that you could probably just call DXproject(project_id) directly in the spots where you use it (example in check_proj_folder_exists below), unless you're particularly invested in keeping DX stuff in utils only (but it doesn't look like that's the case). If you do want to keep it, you should mock out the call to DX when testing it, so you aren't really making dx calls.
</blockquote></details>

This was added to return a boolean to check instead of needing to manually call DXProject(project_id) and handle the error
___
*[`tests/test_utils.py` line 50 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKyYuV-2IoQRMUVf0H:-NrtzBRv3qK67Vcww_XB:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L50)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Note that you still need to update  the Raises section of your docs for get_prod_vep_config
Right now it has Exception, should be RuntimeError
Check CTRL+F check your other 'Raises' sections for the same error please
</blockquote></details>

Done.
___
*[`tests/test_utils.py` line 69 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKyw_WBTjVXLvf2eSf:-NruF5fS2cL4q_KPj7WG:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_utils.py#L69)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Again, you need to patch DX things here even if it's invalid input. You don't want it hitting the API at all if possible
</blockquote></details>

Done.
___
*[`tests/test_vep_testing.py` line 9 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL-BJ59SxNZtYbp6jw:-Nru-rpS9OidjycK3wsH:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L9)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Still in progress?
</blockquote></details>

Done.
___
*[`tests/test_vep_testing.py` line 31 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL-Xbi8k__ONwZEX-X:-Nru-vnSChQ5mkg8xcaQ:bsrlkt4) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L31)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I want to see that the contents of the output match what you want too - right now you're just checking whether Python can string-concatenate to make your output file name.
</blockquote></details>

This relies on mocking a bash script in python, which I don't know how to perform
___
*[`tests/test_vep_testing.py` line 44 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL-pyiCb8n9w-QU1Qj:-Nru5MoV0DbJx2kRcawV:b-qc1jzl) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L44)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I want to see tests for this in failure states, e.g. when it has FileNotFoundError and FileExistsError
I'd also like tests for file contents rather than just file name (example shown earlier)
</blockquote></details>

This seems out of scope for this PR and will be covered in the next one
___
*[`tests/test_vep_testing.py` line 63 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL0Njz8KwHrkNJ-5Wt:-Nru7HDXCcmupA-5NDwn:bql0wap) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L63)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Can you put more projects in here, to check that the _most recent_ one is being fetched, rather than just a random one?
</blockquote></details>

I have added multiple projects to the list. However, I don't see how I can check that the most recent project is being fetched without making an API call to DNAnexus
___
*[`bin/vep_config_update.py` line 130 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH67Kw8tUAr8EP6HVr:-NrtanT-B1Rs7xQutEfn:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/vep_config_update.py#L130)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

run_vep_config_update would benefit from having a lot of its code refactored into smaller functions, which run_vep_config_update then calls. Even if a lot of these functions don't get reused, this will make it much easier to read, and probably to unit test. Currently run_vep_config_update doesn't have any code coverage. It it's just coordinating a few functions that's OK, but it's 300 lines containing most of the application logic, which gets a bit hairy.

The 'switch to new branch' section of code, or perhaps the section in t [...]

2024-03-11 14:16 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 28 of 48 files reviewed, 54 unresolved discussions (waiting on @corbin-chris, @JasonLing95, @jethror1, and @patch)

___
*[`tests/test_inspect_vep_logs.py` line 70 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKsBku2ugTZJ56o4Of:-Nshq-NkCEJFNtXZoI2A:b1e7gpm) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_inspect_vep_logs.py#L70)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

It doesn't look like you're testing generate_test_summary fully here? You only assert that it makes the right filename. You don't try to make sure that expected lines such as these, are actually written to the file:
f.write(f"Overall testing result: {test\_results}\\n\\n")
f.write(f"DNAnexus Job ID: {job\_id}\\n\\n")
f.write(f"Name of new config file: {config\_name}\\n")

You need to use .assert_has_calls() for that bit! Once you've worked it out, please revisit any other file-writing code you've written and test that it writes the correct thing. 

Below, I have some example code which tests that the correct strings have been written to a mock file, below. It's from an Eris branch which is still in progress. Feel free to adapt it. Note I use the context manager 'with patch' for my mock_open(), not the decorator '@patch', so you'll need to remove some of my indenting to make it work for you:
</blockquote></details>

Done. An extensive check is carried out for all the file contents written to. Similar checks will be added for all other relevant unit tests in the next PR


<!-- Sent from Reviewable.io -->

2024-03-12 16:40 UTC, corbin-chris requested changes
> Reviewed 4 of 11 files at r20, 6 of 14 files at r21, 7 of 9 files at r22, 1 of 1 files at r23, 7 of 7 files at r24, all commit messages.
> Dismissed @JasonLing95 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: all files reviewed, 29 unresolved discussions (waiting on @JasonLing95, @jethror1, and @PolarisAstrum-NHS)

___
*[`tests/test_make_vep_test_configs.py` line 22 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKwOGO5-qGO9y2Y3Yv:-NsnWNXT018jnv1Kr7xz:bh7dck6) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_make_vep_test_configs.py#L22)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

This just checks that the code executes successfully. Otherwise I'd need to use the file system
</blockquote></details>

Done you can definitely do this with mocks which lets you avoid the file system, but I'll show you in a less chunky PR
___
*[`tests/test_progress_tracker.py` line 29 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH27435uiar6lG80EG:-NsnW_OK8b9S80zdrgx0:bdrijsk) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_progress_tracker.py#L29)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Writing these unit tests is going to be very difficult due to mocks of local functions still causing problems. These additions seem out of scope for this PR and will be added in the next PR
</blockquote></details>

Done fine by me
___
*[`tests/test_vep_testing.py` line 63 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrL0Njz8KwHrkNJ-5Wt:-NsnRHHb-AlvotLY9Sn3:b618xgq) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_vep_testing.py#L63)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

I have added multiple projects to the list. However, I don't see how I can check that the most recent project is being fetched without making an API call to DNAnexus
</blockquote></details>

Done it looks like you've done what I wanted anyway, by having more than 1 project dictionary in the mock's return value.
___
*[`bin/vep_config_update.py` line 130 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrH67Kw8tUAr8EP6HVr:-NsOcb6O8oerJoxLCLWs:binbuqd) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/vep_config_update.py#L130)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done Looks better
___
*[`bin/annotation/get_clinvar_files.py` line 40 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrHG_4eCCeY-I2Y-1dH:-NsOZoDLAQobjCbkH2ma:b-896fjb) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/annotation/get_clinvar_files.py#L40)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

The common meaning is the same as meaning I'm using. In this case, you can replace the word "latest" with "most recent" and I have to remove any possible ambiguity. To further clarify, setting the "latest_time" variable to an arbitrarily early date is analogous to setting the value to zero (i.e., the default value). This is to ensure that the variable "lastest_time" will always be less than the first date encountered in the list compared against in the line "if latest_time < date_object:"
</blockquote></details>

Done 
___
*[`bin/annotation/get_clinvar_files.py` line 55 at r22](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsO_WES9jPgzvvpwfYY:-NsO_WES9jPgzvvpwfYZ:b-vc0rbw) ([raw file](https://github.com/eastgenomics/prometheus/blob/57737ae0cae3da6a3fb332eef821115dc9eca42d/bin/annotation/get_clinvar_files.py#L55)):*
> ```Python
>             ftp_vcf = file_name
>             ftp_vcf_ver = str(ftp_vcf.split("_")[1].split(".")[0])
>             date_object = datetime.strptime(str(ftp_vcf_ver), '%Y%m%d').date()
> ```

Please call 'date_object' something more informative, like 'clinvar_file_date' or 'vcf_file_date'. I struggled to understand this section at first and that would have helped.
___
*[`bin/util/progress_tracker.py` line 155 at r24](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsnU8h_9MOYBpPLqax_:-NsnU8h_9MOYBpPLqaxa:bc6tl7v) ([raw file](https://github.com/eastgenomics/prometheus/blob/56a2a2bdcbe02577d3e4d0d1ccccf59372fa84e6/bin/util/progress_tracker.py#L155)):*
> ```Python
>                 review = file_name
>                 find_dx_file(
>                     self.dev_proj_id, folder, review, False
> ```

Please get rid of 'review = file_name' and just pass file_name to find_dx_file() instead
___
*[`bin/util/vep_testing.py` line 121 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrKZhLI7XtRrCxK07z3:-NsnExlq0UxkyOlXFH1T:bgnkc8f) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/util/vep_testing.py#L121)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Could you show me the approach again please? It seems to have been lost within the PR comments. Searching for "loop" or "dictionaries" doesn't bring the comment up
</blockquote></details>

No and I'm not doing it again. 
Done 
___
*[`bin/util/vep_testing.py` line 158 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrK_89d0hKX81b-hQ48:-NsnFBF764o2iiyRn40e:b-i01wd6) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/bin/util/vep_testing.py#L158)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Same as my above comment. I can't find your previous "looping over dictionaries" explanation on reviewable
</blockquote></details>

No. Done 
___
*[`tests/test_compare_annotation.py` line 166 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrGybBr7-5tKouUWJzb:-NsnVYi2A6UlTsBiPKpJ:bf8qkv0) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_compare_annotation.py#L166)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done it's covered now
___
*[`tests/test_compare_annotation.py` line 240 at r19](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NrGznOt-3wnUeqjec3o:-NsnVgP4D9nUrvxeXKXr:bb6un1j) ([raw file](https://github.com/eastgenomics/prometheus/blob/9b404c8077abb148eb03c41e260c19bb8f8079a9/tests/test_compare_annotation.py#L240)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-03-13 08:32 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 46 of 48 files reviewed, 29 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/annotation/get_clinvar_files.py` line 55 at r22](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsO_WES9jPgzvvpwfYY:-NsqveRt2GSGMzhPN1u4:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/57737ae0cae3da6a3fb332eef821115dc9eca42d/bin/annotation/get_clinvar_files.py#L55)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please call 'date_object' something more informative, like 'clinvar_file_date' or 'vcf_file_date'. I struggled to understand this section at first and that would have helped.
</blockquote></details>

Done.
___
*[`bin/util/progress_tracker.py` line 155 at r24](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsnU8h_9MOYBpPLqax_:-NsqwBxE683UEvY040D7:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/56a2a2bdcbe02577d3e4d0d1ccccf59372fa84e6/bin/util/progress_tracker.py#L155)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please get rid of 'review = file_name' and just pass file_name to find_dx_file() instead
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-13 09:28 UTC, corbin-chris approved these changes
> Reviewed 2 of 2 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: all files reviewed, 27 unresolved discussions (waiting on @JasonLing95 and @jethror1)



<!-- Sent from Reviewable.io -->

2024-03-13 11:33 UTC, JasonLing95 requested changes
> Reviewed 1 of 16 files at r3, 3 of 19 files at r4, 2 of 21 files at r5, 10 of 30 files at r17, 5 of 15 files at r18, 1 of 4 files at r19, 3 of 11 files at r20, 5 of 14 files at r21, 3 of 9 files at r22, 1 of 1 files at r23, 6 of 7 files at r24, 2 of 2 files at r25.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: all files reviewed, 32 unresolved discussions (waiting on @jethror1 and @PolarisAstrum-NHS)

___
*[`bin/util/utils.py` line 123 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrTzfT3q_fNRfr1ys-:-NsrTzfU-ZhE9tEHd_0P:b-5hqwsa) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L123)):*
> ```Python
> 
>     # if no recent version could be found
>     if recent_version == "":
> ```

might want to use strip() to avoid whitespace scenario
___
*[`bin/util/utils.py` line 203 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrUqr6-hUT6BXwk__-:-NsrUqr6-hUT6BXwk__0:bspk2ow) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L203)):*
> ```Python
>         list[str]: name of latest file
>     """
>     regex = r"[0-9]+\.[0-9]+\.[0-9]+"
> ```

felt like this can be better dealt with by packaging.version rather than using regex. This regex limit the version parsing to three digits e.g. 1.1.1 but could there be chances that version is 1.1 instead
___
*[`bin/util/utils.py` line 243 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrVS14C-gdaDxT6GKM:-NsrVS14C-gdaDxT6GKN:b-xgiea) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L243)):*
> ```Python
>         list (str): list of DNAnexus file IDs
>     """
>     if folder_path == "":
> ```

strip() to prevent whitespace
___
*[`bin/util/utils.py` line 401 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrZMMg3qyRrbdsEapN:-NsrZMMg3qyRrbdsEapO:bbv46s8) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L401)):*
> ```Python
> 
>     flat_config = flatten(config)
>     for key in flat_config:
> ```

how deep are you going into the dict, seems like you're only searching the keys of the dict (level 1) - felt like flatten in this case is unnecessary?
___
*[`bin/util/utils.py` line 432 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrZcHr4TPFXCXugyH1:-NsrZcHs5elQM9kQPHuR:b-yuhohh) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L432)):*
> ```Python
>     """
>     config_filename = glob.glob(json_path_glob)[0]
>     with open(config_filename, "r") as json_file:
> ```

future upgrade might be better to have a file opener function which raise Exception if the file is not present


<!-- Sent from Reviewable.io -->

2024-03-13 12:46 UTC, jethror1 reviewed
> Reviewed 1 of 30 files at r17, 1 of 15 files at r18, 1 of 14 files at r21, 1 of 9 files at r22, 1 of 2 files at r25.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: all files reviewed, 5 unresolved discussions (waiting on @PolarisAstrum-NHS)



<!-- Sent from Reviewable.io -->

2024-03-13 12:46 UTC, jethror1 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: all files reviewed, 5 unresolved discussions (waiting on @PolarisAstrum-NHS)



<!-- Sent from Reviewable.io -->

2024-03-13 13:37 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 46 of 48 files reviewed, 5 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/util/utils.py` line 123 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrTzfT3q_fNRfr1ys-:-NsrsAlq8Z5FF9hY9gY5:bsuigz4) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L123)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

might want to use strip() to avoid whitespace scenario
</blockquote></details>

Before, "" was used as the default value. I've changed it to None to make things clearer
___
*[`bin/util/utils.py` line 203 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrUqr6-hUT6BXwk__-:-NsruHPV7gDByiUTts6C:b7cd47s) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L203)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

felt like this can be better dealt with by packaging.version rather than using regex. This regex limit the version parsing to three digits e.g. 1.1.1 but could there be chances that version is 1.1 instead
</blockquote></details>

Done. Added regex to find anything after the "v" denoting version until the file extension, then use packaging.version to validate it as a valid version number
___
*[`bin/util/utils.py` line 243 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrVS14C-gdaDxT6GKM:-NsrzqiW45N3cnQ7WZkF:b-896fix) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L243)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

strip() to prevent whitespace
</blockquote></details>

Done.
___
*[`bin/util/utils.py` line 401 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrZMMg3qyRrbdsEapN:-Nss-7LJB_vkUonVr1dH:bekh5yj) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L401)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

how deep are you going into the dict, seems like you're only searching the keys of the dict (level 1) - felt like flatten in this case is unnecessary?
</blockquote></details>

For now yes, it's not searching beyond level 1. However, in future flatten may be needed for more complex cases
___
*[`bin/util/utils.py` line 432 at r25](https://reviewable.io/reviews/eastgenomics/prometheus/3#-NsrZcHr4TPFXCXugyH1:-Nss-UiM8v3crPf0xqBh:bozjr4w) ([raw file](https://github.com/eastgenomics/prometheus/blob/7729452197f43448a18ac27852c8a9b7f1e16fbd/bin/util/utils.py#L432)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

future upgrade might be better to have a file opener function which raise Exception if the file is not present
</blockquote></details>

Thanks, I've made a note of that to add to a future version


<!-- Sent from Reviewable.io -->

2024-03-13 13:43 UTC, JasonLing95 requested changes
> Reviewed 1 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @corbin-chris, @jethror1, and @PolarisAstrum-NHS)

___
*[`bin/util/utils.py` line 219 at r26](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nss2FAq1xW_7bT6efTB:-Nss2FAq1xW_7bT6efTC:b-ua00em) ([raw file](https://github.com/eastgenomics/prometheus/blob/a289a1e06b8930839ac9cb3258acec534a0c9dce/bin/util/utils.py#L219)):*
> ```Python
>             # if version is in invalid format continue
>             continue
>         if version > latest_version:
> ```

shouldn't this be version_parsed > latest_version


<!-- Sent from Reviewable.io -->

2024-03-13 13:53 UTC, PolarisAstrum-NHS reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @corbin-chris, @JasonLing95, and @jethror1)

___
*[`bin/util/utils.py` line 219 at r26](https://reviewable.io/reviews/eastgenomics/prometheus/3#-Nss2FAq1xW_7bT6efTB:-Nss4Oqs6Osj4mHGfrD7:b-qx26sm) ([raw file](https://github.com/eastgenomics/prometheus/blob/a289a1e06b8930839ac9cb3258acec534a0c9dce/bin/util/utils.py#L219)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

shouldn't this be version_parsed > latest_version
</blockquote></details>

Thanks for spotting that! Yes, it should have been version_parsed


<!-- Sent from Reviewable.io -->

2024-03-13 14:07 UTC, JasonLing95 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: 47 of 48 files reviewed, all discussions resolved (waiting on @corbin-chris and @jethror1)



<!-- Sent from Reviewable.io -->

2024-03-13 14:27 UTC, JasonLing95 approved these changes
> Reviewed 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PolarisAstrum-NHS)



<!-- Sent from Reviewable.io -->

2024-03-13 14:27 UTC, corbin-chris approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/prometheus/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PolarisAstrum-NHS)



<!-- Sent from Reviewable.io -->

2024-03-13 14:30 UTC, merged